### ISSUE TITLE
'unblockneteasemusic' 不是内部或外部命令，也不是可运行的程序 或批处理文件。

### ISSUE THREAD

**Issue by wordscode** [UnblockNeteaseMusic/server#1003]
### Bug 描述

运行
npm install @unblockneteasemusic/server
yarn add @unblockneteasemusic/server # for Yarn users
npx -p @unblockneteasemusic/server unblockneteasemusic
结果如上，报这个错误是不是我得加path什么的？

### 日志内容

C:\czkinstall\CloudMusic\server-0.27.0>npm install @unblockneteasemusic/server
npm WARN deprecated @types/pino-std-serializers@4.0.0: This is a stub types definition. pino-std-serializers provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/pino-pretty@5.0.0: This is a stub types definition. pino-pretty provides its own type definitions, so you do not need this installed.

added 592 packages, and audited 593 packages in 10s

59 packages are looking for funding
  run `npm fund` for details

4 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

C:\czkinstall\CloudMusic\server-0.27.0>yarn add @unblockneteasemusic/server
➤ YN0000: ┌ Resolution step
➤ YN0061: │ @types/pino-pretty@npm:5.0.0 is deprecated: This is a stub types definition. pino-pretty provides its own type definitions, so you do not need this installed.
➤ YN0061: │ @types/pino-std-serializers@npm:4.0.0 is deprecated: This is a stub types definition. pino-std-serializers provides its own type definitions, so you do not need this installed.
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ @npmcli/move-file@npm:2.0.1 is deprecated: This functionality has been moved to @npmcli/fs
➤ YN0000: └ Completed in 7s 524ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yargs-parser@npm:20.2.9 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs-parser@npm:21.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:16.2.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:17.6.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 3s 113ms
➤ YN0000: ┌ Link step
➤ YN0031: │ One or more node_modules have been detected and will be removed. This operation may take some time.
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed in 1s 504ms
➤ YN0000: Done with warnings in 12s 261ms

C:\czkinstall\CloudMusic\server-0.27.0>npx -p @unblockneteasemusic/server unblockneteasemusic
'unblockneteasemusic' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

### 网易云音乐版本号

2.10.6

### 操作系统

win10

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint（仅 macOS 或 iOS）。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
- 不要混用 npm 和 yarn，我们已经不使用 npm。
- 这个运行方法只在基于 linux 的系统上测试过，windows 推荐直接下载 actions 里面的预构建二进制。

**Comment by pan93412** [comment]
```
npx -p @unblockneteasemusic/server@0.27.1 unblockneteasemusic
```

試試看顯式指定版本？
