### ISSUE TITLE
默认窗口大小

### ISSUE THREAD

**Issue by renmoren** [UnblockNeteaseMusic/server#1016]
### 需求描述

希望软件打开后界面默认为全屏，或添加调节该功能的选项，谢谢

### 网易云音乐版本号

027

### 操作系统

Windows 11 22H2

**Comment by 1715173329** [comment]
unblockneteasemusic 为命令行工具，不存在严格意义上的界面，也没有任何全屏的必要。
本脚本无法改变网易云音乐程序自身的行为。
