### ISSUE TITLE
如何获取网易云当前的播放歌曲名称

### ISSUE THREAD

**Issue by LastStranger** [UnblockNeteaseMusic/server#1022]
### 需求描述

目前我只能在控制台看到被代理的歌曲名称, 有什么办法可以获取到未被代理的歌曲?

**Comment by 1715173329** [comment]
你自己在听什么歌你不知道？

**Comment by LastStranger** [comment]
我想拿到网易云当前播放音乐的歌曲信息,然后把当前播放的歌曲名称信息传给另外一个软件,但是目前我只能拿到被代理的歌曲信息, 所以想问问有什么办法能获取当前播放音乐的信息,无论当前播放的歌曲是否被代理过的

**Comment by ReviveUnblockNCMInstaller** [comment]
> 我想拿到网易云当前播放音乐的歌曲信息,然后把当前播放的歌曲名称信息传给另外一个软件,但是目前我只能拿到被代理的歌曲信息, 所以想问问有什么办法能获取当前播放音乐的信息,无论当前播放的歌曲是否被代理过的

你可以新建一个空 `provider` 然后在 `search` 中读取相关信息，或使用 [BetterNCM](https://github.com/MicroCBer/BetterNCM) 的 `betterncm.ncm.getPlayingSong()`
