### ISSUE TITLE
windows服务失效，也不能重新安装

### ISSUE THREAD

**Issue by Xu316556406** [UnblockNeteaseMusic/server#1039]
### Bug 描述

安装提示
D:\Program Files (Small Often)\UnblockNeteaseMusic>node ./nw.js
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module 'node-windows'
Require stack:
- D:\Program Files (Small Often)\UnblockNeteaseMusic\nw.js
[90m    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)[39m
[90m    at Module._load (node:internal/modules/cjs/loader:920:27)[39m
[90m    at Module.require (node:internal/modules/cjs/loader:1141:19)[39m
[90m    at require (node:internal/modules/cjs/helpers:110:18)[39m
    at Object.<anonymous> [90m(D:\Program Files (Small Often)\UnblockNeteaseMusic\[39mnw.js:1:17[90m)[39m
[90m    at Module._compile (node:internal/modules/cjs/loader:1254:14)[39m
[90m    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)[39m
[90m    at Module.load (node:internal/modules/cjs/loader:1117:32)[39m
[90m    at Module._load (node:internal/modules/cjs/loader:958:12)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [ [32m'D:\\Program Files (Small Often)\\UnblockNeteaseMusic\\nw.js'[39m ]
}

Node.js v18.15.0

D:\Program Files (Small Often)\UnblockNeteaseMusic>

### 预期行为

正常 使用、正常安装

### 实际行为

正常使用突然无法播放，查看windows服务未启动，重新运行node ./nw.js也提示如上

### 复现步骤

100%

### 日志内容

D:\Program Files (Small Often)\UnblockNeteaseMusic>node ./nw.js
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module 'node-windows'
Require stack:
- D:\Program Files (Small Often)\UnblockNeteaseMusic\nw.js
[90m    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)[39m
[90m    at Module._load (node:internal/modules/cjs/loader:920:27)[39m
[90m    at Module.require (node:internal/modules/cjs/loader:1141:19)[39m
[90m    at require (node:internal/modules/cjs/helpers:110:18)[39m
    at Object.<anonymous> [90m(D:\Program Files (Small Often)\UnblockNeteaseMusic\[39mnw.js:1:17[90m)[39m
[90m    at Module._compile (node:internal/modules/cjs/loader:1254:14)[39m
[90m    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)[39m
[90m    at Module.load (node:internal/modules/cjs/loader:1117:32)[39m
[90m    at Module._load (node:internal/modules/cjs/loader:958:12)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [ [32m'D:\\Program Files (Small Often)\\UnblockNeteaseMusic\\nw.js'[39m ]
}

Node.js v18.15.0

D:\Program Files (Small Often)\UnblockNeteaseMusic>

### 网易云音乐版本号

2.9.6

### 操作系统

win10 21h2

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint（仅 macOS 或 iOS）。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
需要先运行 yarn install

**Comment by Xu316556406** [comment]
多谢，我试试，正常使用大半年了，最近2天突然失效了

**Comment by Xu316556406** [comment]
大佬，麻烦您在帮我看看

D:\Program Files (Small Often)\UnblockNeteaseMusic>npm install --global yarn

changed 1 package in 2s

D:\Program Files (Small Often)\UnblockNeteaseMusic>yarn install
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 241ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 332ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed
➤ YN0000: Done with warnings in 0s 795ms

D:\Program Files (Small Often)\UnblockNeteaseMusic>node ./nw.js
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module 'node-windows'
Require stack:
- D:\Program Files (Small Often)\UnblockNeteaseMusic\nw.js
[90m    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)[39m
[90m    at Module._load (node:internal/modules/cjs/loader:920:27)[39m
[90m    at Module.require (node:internal/modules/cjs/loader:1141:19)[39m
[90m    at require (node:internal/modules/cjs/helpers:110:18)[39m
    at Object.<anonymous> [90m(D:\Program Files (Small Often)\UnblockNeteaseMusic\[39mnw.js:1:17[90m)[39m
[90m    at Module._compile (node:internal/modules/cjs/loader:1254:14)[39m
[90m    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)[39m
[90m    at Module.load (node:internal/modules/cjs/loader:1117:32)[39m
[90m    at Module._load (node:internal/modules/cjs/loader:958:12)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [ [32m'D:\\Program Files (Small Often)\\UnblockNeteaseMusic\\nw.js'[39m ]
}

Node.js v18.15.0

**Comment by NicoYaZaW** [comment]
这里有详细的说明，简单来说你可以直接在项目根目录下执行
```
npm install -g node-windows
npm link node-windows
```
然后就可以使用 `node ./nw.js`
[https://github.com/coreybutler/node-windows](url)
