### ISSUE TITLE
windows版本安装之后，网易云音乐客户端设置好代理之后重启之后提示网络连接失败请重试

### ISSUE THREAD

**Issue by cuijg** [UnblockNeteaseMusic/server#1040]
### Bug 描述

windows版本安装之后，网易云音乐客户端设置好代理之后重启之后提示网络连接失败请重试

### 日志内容

INFO: (app) HTTP Server running @ http://0.0.0.0:80
INFO: (app) HTTPS Server running @ http://0.0.0.0:443

### 网易云音乐版本号

2.10.6

### 操作系统

window10

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint（仅 macOS 或 iOS）。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by naiveclub** [comment]
我今天在服务器上更新了一下程序，ios上面能用，但是在Windows版本的客户端里面，使用http代理之后，一直显示网络连接错误。。。这种情况是要在Windows上安装证书吗？

**Comment by cuijg** [comment]
我的在window上一直都是网络连接错误，ios上没试

**Comment by naiveclub** [comment]
> 我的在window上一直都是网络连接错误，ios上没试

好兄弟，你安装一下证书看看，我把证书放到  受信任的根证书颁发机构    ，之后重启客户端就能用了，而且也能解锁

**Comment by cuijg** [comment]
兄弟，安装那个证书呢，是ca.crt吗，windows怎么安装呀，双击直接安装？

**Comment by naiveclub** [comment]
> 兄弟，安装那个证书呢，是ca.crt吗，windows怎么安装呀，双击直接安装？

是ca.crt，具体的安装步骤看这里[https://github.com/UnblockNeteaseMusic/server/discussions/426](url)

**Comment by cuijg** [comment]
<img width="722" alt="捕获" src="https://user-images.githubusercontent.com/23398521/229275762-f10e5059-e55f-4fe6-9187-07d2384119cf.PNG">
都都有这张证书了，还是网络连接失败，请重试

**Comment by cuijg** [comment]
用windows搭建服务试了下，好了；看来是我docker服务的问题，感谢

**Comment by cuijg** [comment]
奇怪，Windows搭建的服务，Windows本机的客户端可以解锁，在安卓手机和苹果手机无法解锁灰色歌曲，手机已经安装了证书，苹果手机点击播放显示网络不给力，无法继续播放；安卓手机弹出因合作方要求，该资源暂时无法收听的弹窗

**Comment by naiveclub** [comment]
> 奇怪，Windows搭建的服务，Windows本机的客户端可以解锁，在安卓手机和苹果手机无法解锁灰色歌曲，手机已经安装了证书，苹果手机点击播放显示网络不给力，无法继续播放；安卓手机弹出因合作方要求，该资源暂时无法收听的弹窗

我是搭建在腾讯云的服务器上面，Windows是用更改代理的方式，ios使用的圈X，都没问题可以正常使用

**Comment by YuriBrightan** [comment]
> > 我的在window上一直都是网络连接错误，ios上没试
> 
> 好兄弟，你安装一下证书看看，我把证书放到 受信任的根证书颁发机构 ，之后重启客户端就能用了，而且也能解锁

我的Windows端也是近几天出的问题 安装证书后就好用了 感谢

**Comment by zxa3256855565** [comment]
我之前也出现了同样问题，而且无论怎么操作都是客户端提示没网，实际原因是，网易云版本太新，你可以尝试降级

**Comment by zxa3256855565** [comment]
> 我之前也出现了同样问题，而且无论怎么操作都是客户端提示没网，实际原因是，网易云版本太新，你可以尝试降级

实测可用版本2.9.10

**Comment by naiveclub** [comment]
> > 我之前也出现了同样问题，而且无论怎么操作都是客户端提示没网，实际原因是，网易云版本太新，你可以尝试降级
> 
> 实测可用版本2.9.10

感谢解答

**Comment by awnag** [comment]
感谢，看来是最新版的网易云客户端封杀了这个功能

**Comment by harveyip** [comment]
Mac（M1，ventura13.3）找两个旧版试了下，2.3.6显示没网络，2.2.0刚开始能听，十多分钟后非灰色可以听，播放灰色则同样显示网络问题且不断自动切歌。

**Comment by LaureatePoet** [comment]
我这边Mac，iOS均失效了，会不会跟软件版本没关系，都G了

**Comment by naiveclub** [comment]
> 我这边Mac，iOS均失效了，会不会跟软件版本没关系，都G了

我刚才在iPhone上试了，网易云版本8.9.61，用的圈X，还是可以解锁的，不过没有用很长时间

**Comment by LaureatePoet** [comment]
> Mac（M1，ventura13.3）找两个旧版试了下，2.3.6显示没网络，2.2.0刚开始能听，十多分钟后非灰色可以听，播放灰色则同样显示网络问题且不断自动切歌。

@harveyip 大佬，Mac商店如何下载旧版App呢，或者您在哪找到的旧版网易云dmg

**Comment by LaureatePoet** [comment]
> > 我这边Mac，iOS均失效了，会不会跟软件版本没关系，都G了
> 
> 我刚才在iPhone上试了，网易云版本8.9.61，用的圈X，还是可以解锁的，不过没有用很长时间

@naiveclub 大佬，我这边iOS安装了网易云旧版8.0.31，但发现我通过该项目的自建网易云解锁节点，还是无法使用。别人的解锁节点有的可以用。

**Comment by awnag** [comment]
桌面版使用旧版2.9.10，今日（2023-04-06）恢复正常使用。昨天还不能用。大家再试试

**Comment by awnag** [comment]
win旧版在此下载：https://blog.amarea.cn/archives/netease-cloudmusic-history-version.html

**Comment by harveyip** [comment]
> win旧版在此下载：https://blog.amarea.cn/archives/netease-cloudmusic-history-version.html

Mac版哭😭，排查了一下，个人猜测是证书到期问题，2023.4.4日20:09分到期，钥匙串里的显示是有效期内，Safari打开https://music.163.com显示过期了，无法在Safari里重新信任（钥匙串根证书已信任）。不确定是不是，等待大佬解惑。

**Comment by naiveclub** [comment]
> > win旧版在此下载：https://blog.amarea.cn/archives/netease-cloudmusic-history-version.html
> 
> 
> 
> Mac版哭😭，排查了一下，个人猜测是证书到期问题，2023.4.4日20:09分到期，钥匙串里的显示是有效期内，Safari打开https://music.163.com 显示过期了，无法在Safari里重新信任（钥匙串根证书已信任）。不确定是不是，等待大佬解惑。

我这边安装的证书都显示2027年4月过期，可以卸载原来的证书，重新安装一下

**Comment by harveyip** [comment]
> > > win旧版在此下载：https://blog.amarea.cn/archives/netease-cloudmusic-history-version.html
> > 
> > 
> > Mac版哭😭，排查了一下，个人猜测是证书到期问题，2023.4.4日20:09分到期，钥匙串里的显示是有效期内，Safari打开https://music.163.com 显示过期了，无法在Safari里重新信任（钥匙串根证书已信任）。不确定是不是，等待大佬解惑。
> 
> 我这边安装的证书都显示2027年4月过期，可以卸载原来的证书，重新安装一下

是的，钥匙串里的UnblockNeteaseMusic Root CA是2027年7月20到期，但是这个信任这个证书后打开music.163.com，证书是无效的，详情里显示music.163.com不被信任，到期时间是2023.4.4。
卸载重装重新信任过证书了，一样的结果。
顺带说一下，同样的配置在iOS下目前是生效的（QuantumultX)，Mac失效时间点也就是4.5号，之前用了一年多了没问题。

**Comment by LaureatePoet** [comment]
同楼下，iOS和Mac均显示
<img width="529" alt="image" src="https://user-images.githubusercontent.com/42093310/230350746-0e5874a5-f679-4584-8c79-ef797e6c8fba.png">

**Comment by pan93412** [comment]
有刪掉舊的 cert 了嗎？

**Comment by LaureatePoet** [comment]
个人觉得是证书有效期只能是1年。
<img width="580" alt="image" src="https://user-images.githubusercontent.com/42093310/230392723-869f5f5b-9f5b-4bca-9bf1-78b6f950f891.png">
<img width="549" alt="image" src="https://user-images.githubusercontent.com/42093310/230392773-c2e912d8-c6e4-4f53-bac6-c4090ae0bd40.png">

@pan93412

**Comment by pan93412** [comment]
> 个人觉得是证书有效期只能是1年。
> <img width="580" alt="image" src="https://user-images.githubusercontent.com/42093310/230392723-869f5f5b-9f5b-4bca-9bf1-78b6f950f891.png">
> <img width="549" alt="image" src="https://user-images.githubusercontent.com/42093310/230392773-c2e912d8-c6e4-4f53-bac6-c4090ae0bd40.png">
> 
> @pan93412 

那你試試看把 generate-cert.sh 的時間改成 365 然後重新安裝一遍呢？

**Comment by LaureatePoet** [comment]
大佬，您是否方便更新一下repo中的cert呢？因为互联网中很多解锁节点都使用此项目进行部署，repo中更新cert文件，所有人都会使用相同的公私钥，这样大家就可以共享解锁节点了。

**Comment by pan93412** [comment]
> 大佬，您是否方便更新一下repo中的cert呢？因为互联网中很多解锁节点都使用此项目进行部署，repo中更新cert文件，所有人都会使用相同的公私钥，这样大家就可以共享解锁节点了。

主要是我想先確認是不是 cert 到期時間造成的問題，如果是的話再統一更換～

**Comment by LaureatePoet** [comment]
好的。我明下午折腾试试。

**Comment by harveyip** [comment]
> 大佬，您是否方便更新一下repo中的cert呢？因为互联网中很多解锁节点都使用此项目进行部署，repo中更新cert文件，所有人都会使用相同的公私钥，这样大家就可以共享解锁节点了。
同求大佬更新一下，感觉是颁发的过期了，可能签名的日期换成多久都不会改变？

**Comment by LaureatePoet** [comment]
> > 大佬，您是否方便更新一下repo中的cert呢？因为互联网中很多解锁节点都使用此项目进行部署，repo中更新cert文件，所有人都会使用相同的公私钥，这样大家就可以共享解锁节点了。
> 
> 主要是我想先確認是不是 cert 到期時間造成的問題，如果是的話再統一更換～

@pan93412 经过重新生成证书，解锁成功！
<img width="580" alt="image" src="https://user-images.githubusercontent.com/42093310/230645396-24a20ef4-3baf-460d-b7bb-002661694cb5.png">

大佬。我自己也制作了镜像上传到了docker hub。公私钥文件是否需要pr

**Comment by harveyip** [comment]
> > > 大佬，您是否方便更新一下repo中的cert呢？因为互联网中很多解锁节点都使用此项目进行部署，repo中更新cert文件，所有人都会使用相同的公私钥，这样大家就可以共享解锁节点了。
> > 
> > 
> > 主要是我想先確認是不是 cert 到期時間造成的問題，如果是的話再統一更換～
> 
> @pan93412 经过重新生成证书，解锁成功！ <img alt="image" width="580" src="https://user-images.githubusercontent.com/42093310/230645396-24a20ef4-3baf-460d-b7bb-002661694cb5.png">
> 
> 大佬。我自己也制作了镜像上传到了docker hub。公私钥文件是否需要pr

确实是证书过期问题么…大佬能否告知一下重新生成具体怎么操作吗？我按照仓库的教程生成的日期一样是过期的。
当然如果仓库的证书能更新一下就更好了，方便我等折腾能力不够的。

**Comment by LaureatePoet** [comment]
@pan93412 
经测试发现是因为项目中的server.*证书过期，有效期days=365，而用户本地安装的CA证书并没有过期。所以需要`renew-cert.sh`，然而我没有`ca.key`，所以无法renew，只能`generate`。

大佬用空可以renew一下server.*证书。

<img width="580" alt="image" src="https://user-images.githubusercontent.com/42093310/230698376-598623f1-0dc0-410c-bf0d-b8a9e7bca9c9.png">
这是我刚测试的，CA和server证书days都是3650，这样就不需要每年renew了。

----
#1044
另外大佬，我pr了`renew-cert.sh`。

**Comment by pan93412** [comment]
cc @1715173329

**Comment by 1715173329** [comment]
370d0d95730e863f1d5567600c2d0048039c0761
上个月已经更新过证书了

**Comment by LaureatePoet** [comment]
我的错，没有pull最新的镜像。

**Comment by pan93412** [comment]
TL;DR 記得更新自己的 Docker image

**Comment by Ni-Cmyk** [comment]
/

> TL;DR 记得更新自己的 Docker 镜像

![微信截图_20230517104822](https://github.com/UnblockNeteaseMusic/server/assets/69250395/08cb5625-b782-4a03-93f4-c918f4bf6929)


感谢提醒 ,      更新证书后 正常了  最新版本 2.10.10 
有一点不明白,我设置了我配置了MBR    但是显示的还是标准 查看Docker日志 又是flac    懵逼....
