### ISSUE TITLE
应版权方要求，此歌曲不支持下载

### ISSUE THREAD

**Issue by Creepercdn** [UnblockNeteaseMusic/server#1042]
### Bug 描述

无法下载未被替换的音频，提示「应版权方要求，此歌曲不支持下载」。

### 日志内容

<details>
<pre><code>INFO: (app) HTTP Server running @ http://0.0.0.0:25443
INFO: (app) HTTPS Server running @ http://0.0.0.0:25444
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (hook) unblockLyricsEffects() has been triggered.
DEBUG: (hook) Unable to apply the local VIP.
DEBUG: (server) TUNNEL
    url: "web.push.126.net:6003"
DEBUG: (server) TUNNEL
    url: "ac.dun.163.com:443"
DEBUG: (server) TUNNEL
    url: "s6.music.126.net:443"
DEBUG: (server) TUNNEL
    url: "st.music.163.com:443"
DEBUG: (server) TUNNEL
    url: "ganbei-hot-update-1258625969.file.myqcloud.com:443"
DEBUG: (server) TUNNEL
    url: "ac.dun.163.com:443"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "acstatic-dun.126.net:443"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (hook) unblockLyricsEffects() has been triggered.
DEBUG: (server) TUNNEL
    url: "gitee.com:443"
DEBUG: (server) TUNNEL
    url: "betterncm.microblock.cc:443"
DEBUG: (server) TUNNEL
    url: "gitee.com:443"
DEBUG: (hook) unblockLyricsEffects() has been triggered.
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (hook) Unable to apply the local VIP.
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (hook) Unable to apply the local VIP.
DEBUG: (server) TUNNEL
    url: "web.push.126.net:6003"
DEBUG: (server) TUNNEL
    url: "p3.music.126.net:443"
DEBUG: (server) TUNNEL
    url: "p4.music.126.net:443"
DEBUG: (server) TUNNEL
    url: "p1.music.126.net:443"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "sentry.music.163.com:443"
DEBUG: (server) TUNNEL
    url: "p2.music.126.net:443"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "s6.music.126.net:443"
DEBUG: (server) TUNNEL
    url: "st.music.163.com:443"
DEBUG: (server) TUNNEL
    url: "st.music.163.com:443"
DEBUG: (server) TUNNEL
    url: "st.music.163.com:443"
DEBUG: (server) TUNNEL
    url: "ac.dun.163.com:443"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "ganbei-hot-update-1258625969.file.myqcloud.com:443"
DEBUG: (server) TUNNEL
    url: "acstatic-dun.126.net:443"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (hook) unblockLyricsEffects() has been triggered.
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (hook) Unable to apply the local VIP.
DEBUG: (server) TUNNEL
    url: "gitee.com:443"
DEBUG: (server) TUNNEL
    url: "betterncm.microblock.cc:443"
DEBUG: (hook) unblockLyricsEffects() has been triggered.
DEBUG: (server) TUNNEL
    url: "gitee.com:443"
DEBUG: (hook) Unable to apply the local VIP.
DEBUG: (server) TUNNEL
    url: "web.push.126.net:6003"
DEBUG: (server) TUNNEL
    url: "p3.music.126.net:443"
DEBUG: (server) TUNNEL
    url: "p4.music.126.net:443"
DEBUG: (server) TUNNEL
    url: "p1.music.126.net:443"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "gitee.com:443"
DEBUG: (server) TUNNEL
    url: "gitee.com:443"
DEBUG: (server) TUNNEL
    url: "gitee.com:443"
DEBUG: (server) TUNNEL
    url: "gitee.com:443"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "acstatic-dun.126.net:443"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "ganbei-hot-update-1258625969.file.myqcloud.com:443"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (hook) unblockLyricsEffects() has been triggered.
DEBUG: (server) TUNNEL
    url: "gitee.com:443"
DEBUG: (server) TUNNEL
    url: "betterncm.microblock.cc:443"
DEBUG: (hook) unblockLyricsEffects() has been triggered.
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (hook) Unable to apply the local VIP.
DEBUG: (hook) Unable to apply the local VIP.
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "ac.dun.163.com:443"
DEBUG: (server) TUNNEL
    url: "web.push.126.net:6003"
DEBUG: (server) TUNNEL
    url: "p3.music.126.net:443"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "p4.music.126.net:443"
DEBUG: (server) TUNNEL
    url: "p1.music.126.net:443"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "provider/qq"
DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "provider/kugou"
DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "provider/kuwo"
DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "provider/migu"
DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "provider/joox"
DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "provider/youtube"
DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "provider/yt-download"
DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "youtube-dl"
DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "yt-dlp"
DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "provider/bilibili"
DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "provider/pyncmd"
DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "provider/find"
DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "hook"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
DEBUG: (server) TUNNEL
    url: "localhost:25444"
</code></pre>
</details>

### 网易云音乐歌曲链接

任何非 VIP 歌曲（下载需要 VIP，播放不需要）

### 网易云音乐版本号

2.10.8

### 操作系统

Windows 10

### 其他信息

betterncm 1.2.0

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint（仅 macOS 或 iOS）。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by windy1021** [comment]
我也遇到了这样的问题，楼主解决了吗

**Comment by Creepercdn** [comment]
duplicate #921
