### ISSUE TITLE
歌曲匹配到了然后貌似链接无法使用？

### ISSUE THREAD

**Issue by huankong233** [UnblockNeteaseMusic/server#1043]
### Bug 描述

问题如题呢

播放歌曲会回复`加载失败`

在服务器使用docker运行
~~~
version: "3"

services:
  163music
    container_name: 163music
    image: pan93412/unblock-netease-music-enhanced:latest
    restart: always
    command: -s -o kuwo kugou bilibili
    ports:
        - 8080:8080
        - 8081:8081
    environment:
        - JSON_LOG=true
        - LOG_LEVEL=debug
        - ENABLE_FLAC=true
        - ENABLE_LOCAL_VIP=true
~~~

别的vip音乐也不行，我看日志匹配的是b站的音乐，但是链接打不开

### 日志内容

55234/01/25 01:13PM 20 pid=1 hostname=d3aeffb104f6 scope=cache cacheStorageId=provider/find msg=Cleaning up the expired caches...
55234/01/25 01:13PM 20 pid=1 hostname=d3aeffb104f6 scope=cache logKey=1984758339 cacheStorageId=provider/find msg=1984758339 hit!
55234/01/25 01:13PM 20 pid=1 hostname=d3aeffb104f6 scope=provider/match source=kuwo info={"name":"すずめ feat.十明","id":1984758339,"alias":["动画电影《すずめの戸締まり》主题曲"],"duration":236390,"album":{"name":"すずめ feat.十明","id":152281043},"artists":[{"name":"RADWIMPS","id":21132},{"name":"十明","id":54169132}],"keyword":"すずめ feat.十明 - RADWIMPS / 十明"} msg=Getting the audio...
55234/01/25 01:13PM 20 pid=1 hostname=d3aeffb104f6 scope=cache cacheStorageId=provider/kuwo msg=Cleaning up the expired caches...
55234/01/25 01:13PM 20 pid=1 hostname=d3aeffb104f6 scope=cache logKey=Something cacheStorageId=provider/kuwo msg=Something hit!
55234/01/25 01:13PM 20 pid=1 hostname=d3aeffb104f6 scope=provider/match source=kugou info={"name":"すずめ feat.十明","id":1984758339,"alias":["动画电影《すずめの戸締まり》主题曲"],"duration":236390,"album":{"name":"すずめ feat.十明","id":152281043},"artists":[{"name":"RADWIMPS","id":21132},{"name":"十明","id":54169132}],"keyword":"すずめ feat.十明 - RADWIMPS / 十明"} msg=Getting the audio...
55234/01/25 01:13PM 20 pid=1 hostname=d3aeffb104f6 scope=cache cacheStorageId=provider/kugou msg=Cleaning up the expired caches...
55234/01/25 01:13PM 20 pid=1 hostname=d3aeffb104f6 scope=cache logKey=Something cacheStorageId=provider/kugou msg=Something hit!
55234/01/25 01:13PM 20 pid=1 hostname=d3aeffb104f6 scope=provider/match source=bilibili info={"name":"すずめ feat.十明","id":1984758339,"alias":["动画电影《すずめの戸締まり》主题曲"],"duration":236390,"album":{"name":"すずめ feat.十明","id":152281043},"artists":[{"name":"RADWIMPS","id":21132},{"name":"十明","id":54169132}],"keyword":"すずめ feat.十明 - RADWIMPS / 十明"} msg=Getting the audio...
55234/01/25 01:13PM 20 pid=1 hostname=d3aeffb104f6 scope=cache cacheStorageId=provider/bilibili msg=Cleaning up the expired caches...
55234/01/25 01:13PM 20 pid=1 hostname=d3aeffb104f6 scope=cache logKey=Something cacheStorageId=provider/bilibili msg=Something hit!
55234/01/25 01:14PM 20 pid=1 hostname=d3aeffb104f6 scope=request msg=Start requesting http://mobi.kuwo.cn/mobi.s?f=kuwo&q=NI8S5evAnmGldi4g47EsqtfDbGsJckckbTQQd2LAgmDPITUWSd51OkjHRFj6xHPE5fnDnpvElvfR6+iIClVO9aQWu004bPoA
55234/01/25 01:14PM 20 pid=1 hostname=d3aeffb104f6 scope=request msg=Start requesting http://trackercdn.kugou.com/i/v2/?key=43065940939c4aeef366e1ee53cb98c4&hash=1ee7a94760b2432e2c211c382235ce1b&appid=1005&pid=2&cmd=25&behavior=play&album_id=70669504
55234/01/25 01:14PM 20 pid=1 hostname=d3aeffb104f6 scope=request msg=Start requesting http://trackercdn.kugou.com/i/v2/?key=fe7efa892b8bfc6133380737e1efe2b8&hash=7b5436d312eaff0943a4eed02ffd6dee&appid=1005&pid=2&cmd=25&behavior=play&album_id=70669504
55234/01/25 01:14PM 20 pid=1 hostname=d3aeffb104f6 scope=request msg=Start requesting http://trackercdn.kugou.com/i/v2/?key=8cb64180e8604921fa2801d22c830cce&hash=84763f014b6775d8fa02e3abb5572fc8&appid=1005&pid=2&cmd=25&behavior=play&album_id=70669504
55234/01/25 01:14PM 20 pid=1 hostname=d3aeffb104f6 scope=request msg=Start requesting https://www.bilibili.com/audio/music-service-c/web/url?rivilege=2&quality=2&sid=3614937
55234/01/25 01:21PM 20 pid=1 hostname=d3aeffb104f6 scope=request msg=Start requesting http://upos-sz-mirrorcos.bilivideo.com/ugaxcode/n221111qn1x557dirn6xi52gvti6w6e7-192k.m4a?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1680858825&gen=playurlv2&os=cosbv&oi=2907890027&trid=ef5925c9052645bc86bea70f2f821319B&mid=0&platform=pc&upsig=286d8826f5779181f319b471e333ff7d&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,1&logo=00000000
55234/01/25 01:28PM 20 pid=1 hostname=d3aeffb104f6 scope=provider/match size=5768535 br=192000 url=http://upos-sz-mirrorcos.bilivideo.com/ugaxcode/n221111qn1x557dirn6xi52gvti6w6e7-192k.m4a?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1680858825&gen=playurlv2&os=cosbv&oi=2907890027&trid=ef5925c9052645bc86bea70f2f821319B&mid=0&platform=pc&upsig=286d8826f5779181f319b471e333ff7d&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,1&logo=00000000 md5= msg=The matched song is:
55234/01/25 01:28PM 20 pid=1 hostname=d3aeffb104f6 scope=provider/match source=bilibili info={"name":"すずめ feat.十明","id":1984758339,"alias":["动画电影《すずめの戸締まり》主题曲"],"duration":236390,"album":{"name":"すずめ feat.十明","id":152281043},"artists":[{"name":"RADWIMPS","id":21132},{"name":"十明","id":54169132}],"keyword":"すずめ feat.十明 - RADWIMPS / 十明"} msg=The audio matched!
55234/01/25 01:28PM 20 pid=1 hostname=d3aeffb104f6 scope=provider/match audioInfo={"name":"すずめ feat.十明","id":1984758339,"alias":["动画电影《すずめの戸締まり》主题曲"],"duration":236390,"album":{"name":"すずめ feat.十明","id":152281043},"artists":[{"name":"RADWIMPS","id":21132},{"name":"十明","id":54169132}],"keyword":"すずめ feat.十明 - RADWIMPS / 十明"} audioData={"size":5768535,"br":192000,"url":"http://upos-sz-mirrorcos.bilivideo.com/ugaxcode/n221111qn1x557dirn6xi52gvti6w6e7-192k.m4a?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1680858825&gen=playurlv2&os=cosbv&oi=2907890027&trid=ef5925c9052645bc86bea70f2f821319B&mid=0&platform=pc&upsig=286d8826f5779181f319b471e333ff7d&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,1&logo=00000000","md5":null} msg=The data to replace:
55234/01/25 01:28PM 30 pid=1 hostname=d3aeffb104f6 scope=provider/match audioId=1984758339 songName=すずめ feat.十明 url=http://upos-sz-mirrorcos.bilivideo.com/ugaxcode/n221111qn1x557dirn6xi52gvti6w6e7-192k.m4a?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1680858825&gen=playurlv2&os=cosbv&oi=2907890027&trid=ef5925c9052645bc86bea70f2f821319B&mid=0&platform=pc&upsig=286d8826f5779181f319b471e333ff7d&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,1&logo=00000000 msg=Replaced: [1984758339] すずめ feat.十明

### 网易云音乐歌曲链接

https://music.163.com/song?id=1984758339

### 网易云音乐版本号

2.10.8

### 操作系统

win10 22H2

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint（仅 macOS 或 iOS）。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by huankong233** [comment]
会不会是因为我部署在远程服务器上，地区是美国，运营商CloudCone

**Comment by huankong233** [comment]
酷狗解析的链接貌似是可用的，但是在网易云中并没有能播放

**Comment by huankong233** [comment]
b站解析出来的我手动试了一下是没问题的，但是不知道为什么网易云里不行
是因为要带什么Header还是什么原因

**Comment by huankong233** [comment]
b站匹配了`Referer`之后就可以正常处理了

**Comment by 1715173329** [comment]
需要设置 endpoint，不然做不了 mitm

**Comment by huankong233** [comment]
> 需要设置 endpoint，不然做不了 mitm

如何设置endpoint是在服务端还是客户端呀
上面说endpoint是苹果才要，我那个是windows

**Comment by 1715173329** [comment]
可以搜其他的 issue。

**Comment by huankong233** [comment]
找到了，在启动选项里加入`-e https://music.163.com`即可
另外谢谢作者的工具，很好用
