### ISSUE TITLE
网络异常

### ISSUE THREAD

**Issue by rsp4jack** [UnblockNeteaseMusic/server#1051]
### Bug 描述

使用一段时间后，NCM 会报告各种网络异常，DevTools 中报告 `net::ERR_EMPTY_RESPONSE`（主要为 EAPI 请求，也有部分其他请求。

日志报告 `ERROR: (provider/match) connect ETIMEDOUT 2408:8719:64:95:8000:0:b00:90:80`。

### 日志内容

https://pastebin.com/2UC4jYXW

### 网易云音乐版本号

2.10.8

### 操作系统

Windows 10

### 其他信息

UnblockNeteaseMusic 版本为 7b579f8

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint（仅 macOS 或 iOS）。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by Creepercdn** [comment]
可以确定是 EAPI 的问题。
![image](https://user-images.githubusercontent.com/47512866/232493775-443e31f6-972e-4997-8648-97074baa0e73.png)

**Comment by Creepercdn** [comment]
![image](https://user-images.githubusercontent.com/47512866/235278824-3459fdb1-55a0-4754-a6ec-646b282489dc.png)
https://interface.music.163.com/eapi/mlivestream/entrance/playpage/get

**Comment by rsp4jack** [comment]
还报告过 music.163.com 连接超时（但是实际上可以正常访问）
```
DEBUG: (request) Start requesting https://music.163.com/api/song/detail?ids=[21398607]
ERROR: (hook) connect ETIMEDOUT 2408:8740:c1fc:302::3:443
    Error: connect ETIMEDOUT 2408:8740:c1fc:302::3:443
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
    errno: -4039
    code: ETIMEDOUT
    syscall: connect
    address: 2408:8740:c1fc:302::3
    port: 443
```

**Comment by rsp4jack** [comment]
更新 UNM 后问题解决。

**Comment by rsp4jack** [comment]
#1134
