### ISSUE TITLE
music.163-my-beloved.com 是不是boom了，pyncmd没用了，直连和代理都不行

### ISSUE THREAD

**Issue by miyukisakurai** [UnblockNeteaseMusic/server#1057]
### Bug 描述

ping不通music.163-my-beloved.com，昨天还是正常用的，现在直连和代理都不行了

### 日志内容

`INFO: (app) HTTP Server running @ http://0.0.0.0:5200
INFO: (app) HTTPS Server running @ http://0.0.0.0:5201
ERROR: (hook) A error occurred in hook.request.after when hooking http://music.163.com/eapi/batch.
    ReferenceError: nVipLevel is not defined
        at /usr/share/unblockneteasemusic/core/app.js:3:10429
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
ERROR: (hook) A error occurred in hook.request.after when hooking http://music.163.com/eapi/batch.
    ReferenceError: nVipLevel is not defined
        at /usr/share/unblockneteasemusic/core/app.js:3:10429
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
ERROR: (hook) A error occurred in hook.request.after when hooking http://music.163.com/eapi/batch.
    ReferenceError: nVipLevel is not defined
        at /usr/share/unblockneteasemusic/core/app.js:3:10429
        at processTicksAndRejections (node:internal/process/task_queues:96:5)`

### 网易云音乐版本号

2.9.5

### 操作系统

windows 10

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint（仅 macOS 或 iOS）。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by miyukisakurai** [comment]
更新过后还是不行欸，显示No audioData!，pyncmd源获取不到了，别的音源和功能是正常的，76.76.21.21那个ip直连代理都试过

**Comment by miyukisakurai** [comment]
> > 更新过后还是不行欸，显示No audioData!，pyncmd源获取不到了，别的音源和功能是正常的，76.76.21.21那个ip直连代理都试过
> 
> 你把问题重新打开吧

我好像没有权限

**Comment by 1715173329** [comment]
`{"code": "500", "message": "Internal error : 匿名登陆失败"}`
可能登录状态掉了？

cc @mos9527

**Comment by miyukisakurai** [comment]
刚刚测试好像修复了

**Comment by 1715173329** [comment]
api 恢复了。虽然网易云音乐 cvip 一年也就 50 块钱而已。

**Comment by miyukisakurai** [comment]
> api 恢复了。虽然网易云音乐 cvip 一年也就 50 块钱而已。

主要直接用pyncm下载的时候不用解锁了比较方便

**Comment by chris7395328** [comment]
> 4/25 今天好像又寄了

刚刚测试没有问题，看看是不是网络原因
