### ISSUE TITLE
开启代理但是显示没有网络

### ISSUE THREAD

**Issue by fbstorm** [UnblockNeteaseMusic/server#1105]
### Bug 描述

软件内代理弄好了，也显示代理可用，但就是显示没有网络，我在其它设备是能用的。
![代理](https://github.com/UnblockNeteaseMusic/server/assets/100028477/25f03e6d-8342-44ef-9807-825b43533d8b)
![窗口](https://github.com/UnblockNeteaseMusic/server/assets/100028477/f18afafb-1b6b-416b-8545-74a3c34c3206)
![没网](https://github.com/UnblockNeteaseMusic/server/assets/100028477/c06f9d08-813b-4100-9cfb-2ac9fb7c914f)
之前装过betterNCM后来删掉了，删完之后这个就用不了了，是不是跟这个有关？

### 日志内容

不会，用的exe，这个怎么调出来

### 网易云音乐版本号

2.10.8

### 操作系统

Win10

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [x] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
去装证书

**Comment by dusuissisi** [comment]
安装一下就好了
https://github.com/UnblockNeteaseMusic/server/discussions/426

**Comment by fbstorm** [comment]
谢谢谢谢，解决了！！谢谢谢谢！
