### ISSUE TITLE
interface.music.163.com 的請求似乎都會失敗

### ISSUE THREAD

**Issue by lekoOwO** [UnblockNeteaseMusic/server#1134]
### Bug 描述

如題
架好之後，music.163.com 的請求沒問題 (music.163.com 的網頁正常)，但 interface.music.163.com 的請求似乎都會失敗導致客戶端無法使用

### 日志内容

```
INFO: (app) HTTP Server running @ http://0.0.0.0.:80
INFO: (app) HTTPS Server running @ http://0.0.0.0:443
```

### 网易云音乐版本号

2.10.10 Patch 1

### 操作系统

Windows 11

### 其他信息

Server 使用 Linux binary 版架設
`LOG=debug NO_CACHE=true SIGN_CERT=/root/certs/server.crt SIGN_KEY=/root/certs/server.key ENABLE_FLAC=true /root/unblockneteasemusic-linux-x64 -o ytdlp bilibili  -p 80:443 -s`

使用軟體內代理會出現此情況
修改 Hosts 的話一開始會一直連接失敗，然後軟體就會 fallback 到他們伺服器的正常 IP 上。

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
很抱歉目前我暂时没有 2.10.10 的环境。请问您的 binary 是从 actions 中下载的吗？

**Comment by lekoOwO** [comment]
> 很抱歉目前我暂时没有 2.10.10 的环境。请问您的 binary 是从 actions 中下载的吗？

是 https://github.com/UnblockNeteaseMusic/server/releases/download/v0.27.1/unblockneteasemusic-linux-x64 這個版本

**Comment by 1715173329** [comment]
目前主分支有一些兼容性修复，但还未发版。
可以试试 https://github.com/UnblockNeteaseMusic/server/suites/13714027090/artifacts/758518935 (https://github.com/UnblockNeteaseMusic/server/actions/runs/5315648887)

**Comment by lekoOwO** [comment]
剛剛嘗試了，似乎沒有改善

**Comment by lekoOwO** [comment]
更新：使用 [evivedUnblockInstaller](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller) 可以使用

**Comment by lekoOwO** [comment]
看起來使用 BetterNCM 版本的時候，請求都會正常發到 music.163.com
但是使用 linux 版的時候，請求都是往 interface.music.163.com 發，然後伺服器不回應就失敗了，我沒看懂原因是什麼

**Comment by 1715173329** [comment]
![image](https://github.com/UnblockNeteaseMusic/server/assets/22235437/a63375cc-4df7-4f9f-b33e-44845e16660b)

开了个虚拟机测了下似乎没有问题，如果你替换了默认的证书，请确保信任了你自己签发的根证书。
参考 https://github.com/UnblockNeteaseMusic/server/discussions/426

**Comment by 1715173329** [comment]
我主要是在路由器上面运行的，也是 linux。不过我没有启用严格模式。
最新版本 v0.27.2 理论上已经默认开启 endpoint。

**Comment by 1715173329** [comment]
可能与 #1140 相关，可以试试

**Comment by lekoOwO** [comment]
似乎跟 #1140 沒有關係

**Comment by lekoOwO** [comment]
先前 LOG 參數下錯了

用 `LOG_LEVEL=DEBUG` 可以得到

```
INFO: (app) HTTP Server running @ http://10.121.124.13:80
INFO: (app) HTTPS Server running @ http://10.121.124.13:443
DEBUG: (server) TUNNEL
    url: "s6.music.126.net:443"
DEBUG: (server) TUNNEL
    url: "st.music.163.com:443"
DEBUG: (server) TUNNEL
    url: "10.121.124.13:443"
DEBUG: (server) TUNNEL
    url: "10.121.124.13:443"
DEBUG: (server) TUNNEL
    url: "10.121.124.13:443"
DEBUG: (server) TUNNEL
    url: "10.121.124.13:443"
DEBUG: (server) TUNNEL
    url: "10.121.124.13:443"
DEBUG: (server) TUNNEL
    url: "10.121.124.13:443"
DEBUG: (server) TUNNEL
    url: "10.121.124.13:443"
DEBUG: (server) TUNNEL
    url: "ac.dun.163yun.com:443"
DEBUG: (server) TUNNEL
    url: "ac.dun.163yun.com:443"
DEBUG: (server) TUNNEL
    url: "ac.dun.163yun.com:443"
```

之類的 log，不過還是沒有資料

**Comment by pan93412** [comment]
沒有 MITM 只有 TUNNEL 很有可能是因為你 TLS 憑證沒有裝好……

**Comment by lekoOwO** [comment]
![image](https://github.com/UnblockNeteaseMusic/server/assets/20151124/d7ba46f8-fb80-4ca6-b2e6-f75b0e2f193e)

應該不是

**Comment by lekoOwO** [comment]
用安卓版的 代理指向伺服器 好像也是只有 TUNNEL

**Comment by SakuraKoi** [comment]
> 先前 LOG 參數下錯了
> 
> 用 `LOG_LEVEL=DEBUG` 可以得到
> 
> ```
> INFO: (app) HTTP Server running @ http://10.121.124.13:80
> INFO: (app) HTTPS Server running @ http://10.121.124.13:443
> DEBUG: (server) TUNNEL
>     url: "s6.music.126.net:443"
> DEBUG: (server) TUNNEL
>     url: "st.music.163.com:443"
> DEBUG: (server) TUNNEL
>     url: "10.121.124.13:443"
> DEBUG: (server) TUNNEL
>     url: "10.121.124.13:443"
> DEBUG: (server) TUNNEL
>     url: "10.121.124.13:443"
> DEBUG: (server) TUNNEL
>     url: "10.121.124.13:443"
> DEBUG: (server) TUNNEL
>     url: "10.121.124.13:443"
> DEBUG: (server) TUNNEL
>     url: "10.121.124.13:443"
> DEBUG: (server) TUNNEL
>     url: "10.121.124.13:443"
> DEBUG: (server) TUNNEL
>     url: "ac.dun.163yun.com:443"
> DEBUG: (server) TUNNEL
>     url: "ac.dun.163yun.com:443"
> DEBUG: (server) TUNNEL
>     url: "ac.dun.163yun.com:443"
> ```
> 
> 之類的 log，不過還是相同錯誤 客戶端很多都是 `net::ERR_EMPTY_RESPONSE` 的錯誤

同样的问题, 有找到解决方案么
使用的最新开发分支编译的版本

**Comment by SakuraKoi** [comment]
破案了, music.163.com的dns解析走梯子了, 解析到了个连不上的ip
```
> ping music.163.com
PING overseasv4.music.ntes53.netease.com (103.126.92.133) 56(84) bytes of data.
^C
--- overseasv4.music.ntes53.netease.com ping statistics ---
9 packets transmitted, 0 received, 100% packet loss, time 8231ms
```

添加-f参数手动指定网易云服务器ip后解决

**Comment by lekoOwO** [comment]
哎，我的也是走梯子了，感謝
