### ISSUE TITLE
有考虑加入一些国外平台的音源吗？

### ISSUE THREAD

**Issue by DestoryG** [UnblockNeteaseMusic/server#1160]
### 需求描述

像Spotify，SoundCloud，Bandcamp等等，目前只有Youtube和Joox

**Comment by 1715173329** [comment]
PR is welcome

**Comment by pan93412** [comment]
SoundCloud 可以考慮，Spotify 有 DRM 問題，原則上是不會做……

**Comment by canc3s** [comment]
Apple music可以做吗
