### ISSUE TITLE
ENABLE_FLAC=true 之後不一定可以取得 FLAC 版本的音訊

### ISSUE THREAD

**Issue by 4860575** [UnblockNeteaseMusic/server#141]
系统环境：debian-10
node版本：v14.17.6
测试歌曲：金池-谁不是
客户端：macos v1.5.10 && macos v2.3.5
启动方式：ENABLE_FLAC=true node ./app.js -p 5200:5201 -s
问题：
1、下载时经常出现“版权提示”，重启几遍客户端后可以解决。在线听没有问题；
2、以前能听的歌是有时会出现灰色，重启几遍客户端后可以解决。
3、同一首歌，下载时有时是mp3（128kbps），重启几次客户端都就能下载flac的了
日志日下：
MITM > music.163.com (ssl)
Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
    at Decipheriv.final (internal/crypto/cipher.js:174:29)
    at decrypt (/root/UnblockNeteaseMusic-b/src/crypto.js:12:58)
    at Object.decrypt (/root/UnblockNeteaseMusic-b/src/crypto.js:23:24)
    at /root/UnblockNeteaseMusic-b/src/hook.js:228:25
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  library: 'digital envelope routines',
  function: 'EVP_DecryptFinal_ex',
  reason: 'wrong final block length',
  code: 'ERR_OSSL_EVP_WRONG_FINAL_BLOCK_LENGTH'
} http://music.163.com/eapi/song/enhance/player/url
MITM > music.163.com (ssl)
[1840450059] 谁不是
http://fsandroid.tx.kugou.com/202109062315/041a3a9b05bb1f75bdcd6b3e2c4a1eb8/G221/M06/1B/13/vZQEAF9F3v6AbNzDADsq36g7MgU107.mp3
MITM > music.163.com (ssl)
TUNNEL > localhost:5201
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
    at Decipheriv.final (internal/crypto/cipher.js:174:29)
    at decrypt (/root/UnblockNeteaseMusic-b/src/crypto.js:12:58)
    at Object.decrypt (/root/UnblockNeteaseMusic-b/src/crypto.js:23:24)
    at /root/UnblockNeteaseMusic-b/src/hook.js:228:25
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  library: 'digital envelope routines',
  function: 'EVP_DecryptFinal_ex',
  reason: 'wrong final block length',
  code: 'ERR_OSSL_EVP_WRONG_FINAL_BLOCK_LENGTH'
} https://music.163.com/eapi/v3/song/detail/
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
[1840450059] 谁不是
http://gc.sycdn.kuwo.cn/be02c1cb1cb24b274ccebdf39daf7de0/613630e3/resource/s3/83/8/836988861.flac
TUNNEL > localhost:5201
MITM > music.163.com (ssl)

**Comment by 1715173329** [comment]
> 3、同一首歌，下载时有时是mp3（128kbps）

音质由音源决定，并行查询时，默认只取第一个返回的信息。

**Comment by 4860575** [comment]
> > 3、同一首歌，下载时有时是mp3（128kbps）
> 
> 音质由音源决定，并行查询时，默认只取第一个返回的信息。

1、但是我启用了“ENABLE_FLAC=true”，为何还返回mp3的音源？
2、加入“-o kuwo”后命中率就很高了。
3、如果不启用“ENABLE_FLAC=true”，同一首歌有时候会下载128kbps，加入“-o kuwo”就能下载320kbps的歌了。
测试歌曲：周杰伦 - 你怎么连话都说不清楚(Live)

**Comment by 1715173329** [comment]
> 1、但是我启用了“ENABLE_FLAC=true”，为何还返回mp3的音源？
> 2、加入“-o kuwo”后命中率就很高了。

`ENABLE_FLAC=true` 代表【尝试】向音源请求高音质信息，但如果该平台没有高音质呢？
酷我本身版权较多，且拥有无损音质信息，自然命中率高。

**Comment by 4860575** [comment]
> > 1、但是我启用了“ENABLE_FLAC=true”，为何还返回mp3的音源？
> > 2、加入“-o kuwo”后命中率就很高了。
> 
> `ENABLE_FLAC=true` 代表【尝试】向音源请求高音质信息，但如果该平台没有高音质呢？
> 酷我本身版权较多，且拥有无损音质信息，自然命中率高。

目前同步了commit 809ad186c45856a6e8c263e8f3173cb3e1ce44ab。启动方式不变。“ENABLE_FLAC=true”启动后，获取的音频都是128kbps。周杰伦的能获取flac。很奇怪
![image](https://user-images.githubusercontent.com/24975201/134769779-b4746604-d3e6-4a36-b271-972b03173a1a.png)

![image](https://user-images.githubusercontent.com/24975201/134769804-3f3da629-1fe8-4efb-bf22-a1505f44ff3a.png)

![image](https://user-images.githubusercontent.com/24975201/134769748-96437f07-d6d2-4ebe-ba8e-60f00d1e99a0.png)

![image](https://user-images.githubusercontent.com/24975201/134769770-7b5de2e3-c607-4bd7-9412-7cfc4552a449.png)

**Comment by pan93412** [comment]
> > > 1、但是我启用了“ENABLE_FLAC=true”，为何还返回mp3的音源？
> > > 2、加入“-o kuwo”后命中率就很高了。
> > 
> > 
> > `ENABLE_FLAC=true` 代表【尝试】向音源请求高音质信息，但如果该平台没有高音质呢？
> > 酷我本身版权较多，且拥有无损音质信息，自然命中率高。
> 
> 目前同步了commit [809ad18](https://github.com/UnblockNeteaseMusic/server/commit/809ad186c45856a6e8c263e8f3173cb3e1ce44ab)。启动方式不变。“ENABLE_FLAC=true”启动后，获取的音频都是128kbps。周杰伦的能获取flac。很奇怪
> 貌似网易有版权的，服务端就没有搜索，没有版权的才去搜索。我听张学友的歌，服务端日志没有输出，周杰伦的就有了。
> ![image](https://user-images.githubusercontent.com/24975201/134769779-b4746604-d3e6-4a36-b271-972b03173a1a.png)
> 
> ![image](https://user-images.githubusercontent.com/24975201/134769804-3f3da629-1fe8-4efb-bf22-a1505f44ff3a.png)
> 
> ![image](https://user-images.githubusercontent.com/24975201/134769748-96437f07-d6d2-4ebe-ba8e-60f00d1e99a0.png)
> 
> ![image](https://user-images.githubusercontent.com/24975201/134769770-7b5de2e3-c607-4bd7-9412-7cfc4552a449.png)

感覺是網易雲音樂拿到張學友的版權了。

**Comment by 4860575** [comment]
> > > > 1、但是我启用了“ENABLE_FLAC=true”，为何还返回mp3的音源？
> > > > 2、加入“-o kuwo”后命中率就很高了。
> > > 
> > > 
> > > `ENABLE_FLAC=true` 代表【尝试】向音源请求高音质信息，但如果该平台没有高音质呢？
> > > 酷我本身版权较多，且拥有无损音质信息，自然命中率高。
> > 
> > 
> > 目前同步了commit [809ad18](https://github.com/UnblockNeteaseMusic/server/commit/809ad186c45856a6e8c263e8f3173cb3e1ce44ab)。启动方式不变。“ENABLE_FLAC=true”启动后，获取的音频都是128kbps。周杰伦的能获取flac。很奇怪
> > 貌似网易有版权的，服务端就没有搜索，没有版权的才去搜索。我听张学友的歌，服务端日志没有输出，周杰伦的就有了。
> > ![image](https://user-images.githubusercontent.com/24975201/134769779-b4746604-d3e6-4a36-b271-972b03173a1a.png)
> > ![image](https://user-images.githubusercontent.com/24975201/134769804-3f3da629-1fe8-4efb-bf22-a1505f44ff3a.png)
> > ![image](https://user-images.githubusercontent.com/24975201/134769748-96437f07-d6d2-4ebe-ba8e-60f00d1e99a0.png)
> > ![image](https://user-images.githubusercontent.com/24975201/134769770-7b5de2e3-c607-4bd7-9412-7cfc4552a449.png)
> 
> 感覺是網易雲音樂拿到張學友的版權了。你可以設定 `MIN_BR` 強制更換成其他音源。

的确，設定 `MIN_BR`后就可以了。太棒了
