### ISSUE TITLE
能否支持 UWP 版本直接修改服务器地址的功能？

### ISSUE THREAD

**Issue by ysc3839** [UnblockNeteaseMusic/server#156]
UWP 版本在关于页面多次 (具体多少次不知道，狂点就对了) 左键点击图标后右键点击一次可以打开服务器地址设置
![image](https://user-images.githubusercontent.com/12028138/133498430-99e69c34-78a7-44c6-8b89-6e8891e2f800.png)
![image](https://user-images.githubusercontent.com/12028138/133498353-de812a89-bd8f-46e8-a07f-425e5a21c2a8.png)
将此处改为 `http://127.0.0.1:8080` 后并不能正常使用，个人猜测是因为请求中不包含 `music.163.com` 的域名。
能否支持这种方法，这样就不需要改 hosts 或者使用代理了。

**Comment by pan93412** [comment]
我那邊沒有 NeteaseMusic UWP，也不太了解你在說什麼 QQ

先幫你標 `help wanted`。

**Comment by lxalano** [comment]
支持的，请检查你的配置，我测试成功了

**Comment by ysc3839** [comment]
@lxalano 请问您是如何配置的呢？我是在前面第二个图中的“服务地址”里填写了`http://127.0.0.1:8080`，重新打开就一直提示网络错误。已经测试过设置系统代理是没问题的。

**Comment by ysc3839** [comment]
使用 nginx 反向代理把 http 头的 Host 改成 `music.163.com` 就能正常使用了。
```
location / {
	proxy_pass http://127.0.0.1:8080;
	proxy_http_version 1.1;
	proxy_buffering off;
	proxy_set_header Host music.163.com;
}
```
