### ISSUE TITLE
每次搜索后都有“WARN: (request)”

### ISSUE THREAD

**Issue by 4860575** [UnblockNeteaseMusic/server#173]
commit:3c905e222dee14a1412bdfc7210a7e5dc4abd661
node:v14.16.0
客户端：Mac os 2.3.6 (862)
启动方式：`MIN_BR=320000 node /root/UnblockNeteaseMusic/app.js -p 6200:6201 -o pyncmd kuwo -s >>/tmp/mp3.log 2>&1 &`
问题：歌曲搜索后过会会出现“WARN: (request) The request timed out, or the requester didn't handle the response.”每次搜索都有
日志如下：

> INFO: (app) HTTP Server running @ http://0.0.0.0:6200
INFO: (app) HTTPS Server running @ http://0.0.0.0:6201
ERROR: (hook) A error occurred in hook.request.after when hooking https://music.163.com/eapi/batch.
    Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
        at Decipheriv.final (internal/crypto/cipher.js:174:29)
        at decrypt (/root/UnblockNeteaseMusic/precompiled/app.js:11044:61)
        at Object.decrypt (/root/UnblockNeteaseMusic/precompiled/app.js:11055:26)
        at /root/UnblockNeteaseMusic/precompiled/app.js:12333:57
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
library: digital envelope routines
function: EVP_DecryptFinal_ex
reason: wrong final block length
code: ERR_OSSL_EVP_WRONG_FINAL_BLOCK_LENGTH
INFO: (provider/match) Replaced: [4225638] Just Getting Older
    audioId: 4225638
    songName: "Just Getting Older"
    url: "http://m801.music.126.net/20210920010339/e67e4b525feee76ea101426b00fcf078/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/8772962493/b773/ff6c/f119/287c16af2acbaa239842540f5bc054ad.mp3"
WARN: (request) The request timed out, or the requester didn't handle the response.
    url: "http://kuwo.cn/search/list?key=Just%20Getting%20OlderOasis"
INFO: (provider/match) Replaced: [1363905876] Everybody
    audioId: 1363905876
    songName: "Everybody"
    url: "http://m8.music.126.net/20210920010420/a62d38f68de93176ce5e821e0730d4d1/ymusic/025c/050f/515a/56504927b22e596d048cf050c0bb86c6.mp3"
WARN: (request) The request timed out, or the requester didn't handle the response.
    url: "http://kuwo.cn/search/list?key=EverybodySteff%20Da%20Campo%20%2F%20David%20Puentez"
INFO: (provider/match) Replaced: [480768667] Sunsetz
    audioId: 480768667
    songName: "Sunsetz"
    url: "http://m701.music.126.net/20210920010543/db9b324fe50c14c2ad199012e8b74564/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/7010053199/7fd3/5a1a/7571/74b1ecf02ea7c6968a50331f748e9270.mp3"
WARN: (request) The request timed out, or the requester didn't handle the response.
    url: "http://kuwo.cn/search/list?key=SunsetzCigarettes%20After%20Sex"

**Comment by pan93412** [comment]
只是表示有請求逾時，若功能正常則可不需理會。

**Comment by 4860575** [comment]
> 只是表示有請求逾時，若功能正常則可不需理會。

在首选的“ pyncmd”已经搜索到了，为何过几秒还要在“kuwo”再次请求？

**Comment by pan93412** [comment]
> > 只是表示有請求逾時，若功能正常則可不需理會。
> 
> 在首选的“ pyncmd”已经搜索到了，为何过几秒还要在“kuwo”再次请求？

UNM 會往所有音源發送查詢請求，然後選擇回應最快的請求。即便如此，剩下未完成的查詢請求，不會在選擇完音源後立即暫停（Node.js 的 HTTP 機制，要等到收到查詢結果之後才能取消運作）。因此，你看到的 kuwo 是跟 pyncmd 同時間請求的。

至於這則錯誤訊息是怎麼回事呢？這個 case 下 kuwo 那端遲遲沒收到查詢結果，所以 UNM 自動把請求取消了。為了讓使用者清楚「是音源的問題，UNM 不是無緣無故取消這個請求的，」所以才會彈出這個警告訊息。通常毋須理會。
