### ISSUE TITLE
启用“ENABLE_FLAC=true”后很多歌曲无法解锁

### ISSUE THREAD

**Issue by 4860575** [UnblockNeteaseMusic/server#174]
commit:3c905e222dee14a1412bdfc7210a7e5dc4abd661
node:v14.16.0
客户端：Mac os 2.3.6 (862)
启动方式：ENABLE_FLAC=true ENABLE_LOCAL_VIP=true node /root/UnblockNeteaseMusic/app.js -p 6200:6201 -o pyncmd kuwo -s >>/tmp/flac.log 2>&1 &
ENABLE_FLAC=true ENABLE_LOCAL_VIP=true node /root/UnblockNeteaseMusic/app.js -p 6200:6201 -s >>/tmp/flac.log 2>&1 &
问题：以上两种方式启动都无法解锁周董的歌曲
日志如下：
`INFO: (app) HTTP Server running @ http://0.0.0.0:5200
INFO: (app) HTTPS Server running @ http://0.0.0.0:5201
(node:1240946) UnhandledPromiseRejectionWarning: TypeError: getBuiltIn(...) is not a constructor
    at /root/UnblockNeteaseMusic-b/precompiled/app.js:11876:33
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1240946) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:1240946) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1240946) UnhandledPromiseRejectionWarning: TypeError: getBuiltIn(...) is not a constructor
    at /root/UnblockNeteaseMusic-b/precompiled/app.js:11876:33
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1240946) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
WARN: (request) The request timed out, or the requester didn't handle the response.
    url: "http://kuwo.cn/search/list?key=%E6%88%91%E8%A6%81%E5%A4%8F%E5%A4%A9%E5%91%A8%E6%9D%B0%E4%BC%A6%20%2F%20%E6%9D%A8%E7%91%9E%E4%BB%A3"
(node:1240946) UnhandledPromiseRejectionWarning: TypeError: getBuiltIn(...) is not a constructor
    at /root/UnblockNeteaseMusic-b/precompiled/app.js:11876:33
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1240946) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
WARN: (request) The request timed out, or the requester didn't handle the response.
    url: "http://kuwo.cn/search/list?key=%E4%B8%80%E5%8F%A3%E6%B0%94%E5%85%A8%E5%BF%B5%E5%AF%B9%E5%91%A8%E6%9D%B0%E4%BC%A6"
WARN: (request) The request timed out, or the requester didn't handle the response.
    url: "http://kuwo.cn/search/list?key=%E5%90%AC%E7%88%B8%E7%88%B8%E7%9A%84%E8%AF%9D%E5%91%A8%E6%9D%B0%E4%BC%A6"
(node:1240946) UnhandledPromiseRejectionWarning: TypeError: getBuiltIn(...) is not a constructor
    at /root/UnblockNeteaseMusic-b/precompiled/app.js:11876:33
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1240946) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)
WARN: (request) The request timed out, or the requester didn't handle the response.
    url: "http://kuwo.cn/search/list?key=%E7%BE%8E%E4%BA%BA%E9%B1%BC%E5%91%A8%E6%9D%B0%E4%BC%A6"`

**Comment by 1715173329** [comment]
这与 `ENABLE_FLAC=true` 没有任何关系。
kuwo 最近改了 api，还在看怎么解决。

**Comment by 4860575** [comment]
> 这与 `ENABLE_FLAC=true` 没有任何关系。
> kuwo 最近改了 api，还在看怎么解决。

怪不得呢，启用flac后下载的都是128kbps的mp3.如果不加‘ENABLE_FLAC=true’下载的反而是320kbps的。

**Comment by pan93412** [comment]
> 这与 `ENABLE_FLAC=true` 没有任何关系。
> kuwo 最近改了 api，还在看怎么解决。

或許不止。不過 precompiled 的 `getBuiltin()` 感覺怪怪的。我找時間修。

**Comment by 1715173329** [comment]
酷我无损 api 寄了，现在只能拿到 320k 的。。
有空去抓包 app 的试试

**Comment by 1715173329** [comment]
> 酷我无损 api 寄了，现在只能拿到 320k 的。。
> 有空去抓包 app 的试试

好像是 request 出了点问题，没有正确传递 user-agent。。
