### ISSUE TITLE
YouTube 音源无法正常工作

### ISSUE THREAD

**Issue by 4860575** [UnblockNeteaseMusic/server#179]
commit:71ac0fcdb921e07fa08ba7a8f1b0f22995152218
node:v14.16.0
客户端：Mac os 2.3.6 (862)
启动方式：ENABLE_FLAC=true ENABLE_LOCAL_VIP=true node /root/UnblockNeteaseMusic/app.js -p 6200:6201  -o bilibili kuwo -s >>/tmp/flac.log 2>&1 &
ENABLE_FLAC=true ENABLE_LOCAL_VIP=true node /root/UnblockNeteaseMusic/app.js -p 6200:6201 -s >>/tmp/flac.log 2>&1 &
问题：
bilibili,youtube源解析的歌曲无法播放；

> ERROR (SongNotAvailable): (provider/match) This song "?" is not available in pyncmd
    SongNotAvailable: This song "?" is not available in pyncmd
        at getAudioFromSource (/root/UnblockNeteaseMusic-b/precompiled/app.js:12071:25)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
INFO: (provider/match) Replaced: [185617] 你好吗
    audioId: 185617
    songName: "你好吗"
    url: "http://upos-sz-mirrorks3.bilivideo.com/ugaxcode/m210227a22swyjzuzvseup2d71tokeci-192k.m4a?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1632122550&gen=playurlv2&os=ks3bv&oi=1020451065&trid=f5dc24e096eb43f3afff066410ea5447B&platform=pc&upsig=7628e65a90661e535c42124fd8b17963&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&bvc=vod&nettype=0&orderid=0,1&logo=00000000"
ERROR (RequestFailed): (provider/match) Failed to get the response. Status code: 403
    RequestFailed: Failed to get the response. Status code: 403
        at check (/root/UnblockNeteaseMusic/precompiled/app.js:12140:53)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
        at async getAudioFromSource (/root/UnblockNeteaseMusic/precompiled/app.js:12073:16)
url: https://r3---sn-a5meknzk.googlevideo.com/videoplayback?expire=1632137232&ei=sBtIYbvuLNqDkgbLmZ_YBg&ip=129.159.44.84&id=o-AOufjMK0VlMsKlKHyhwNVmtO2s5BjvySRliFLcDbd7zt&itag=140&source=youtube&requiressl=yes&mh=pi&mm=31%2C26&mn=sn-a5meknzk%2Csn-n4v7sne7&ms=au%2Conr&mv=m&mvi=3&pl=23&initcwndbps=1143750&vprv=1&mime=audio%2Fmp4&ns=I-3nILLabU4-tMA6HX725WwG&gir=yes&clen=3584925&dur=221.448&lmt=1551766407005638&mt=1632115249&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5535432&n=F0SEmh5Ue4K_iFQEX&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAONKNT11lsNW2rT03feNhNZE8oOPFGE-DOHL8bq7lL81AiEAqJOS8OTMCk5n_jPOpeEc3LTiDwqUfY9mvCbzUAFYX3E%3D&sig=0QJ8wRAIgajV4QglkuK9OXp-4_DXJ6Uq3ACXpBUyr4sbHEkJzl6cCIDFZ9pUKthdJBxclGL8lu5a8_tgF61He_OWJIB8OLei0
code: 403
以上情况在不启用‘ENABLE_FLAC=true’时同样出现

**Comment by pan93412** [comment]
看起來 UNM 已經把音源替換成 `Bilibili` 的了：

```
INFO: (provider/match) Replaced: [185617] 你好吗
audioId: 185617
songName: "你好吗"
url: "http://upos-sz-mirrorks3.bilivideo.com/ugaxcode/m210227a22swyjzuzvseup2d71tokeci-192k.m4a?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1632122550&gen=playurlv2&os=ks3bv&oi=1020451065&trid=f5dc24e096eb43f3afff066410ea5447B&platform=pc&upsig=7628e65a90661e535c42124fd8b17963&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&bvc=vod&nettype=0&orderid=0,1&logo=00000000"
```

`youtube` 源現在有些問題。我建議你在自己的伺服器或電腦上安裝 `youtube-dl`，然後改用 `youtubedl` 源。

**Comment by pan93412** [comment]
如果 UNM 替換後還是顯示「無法播放」，請重新啟動 NeteaseMusic。如果還是不行，試試看清掉快取之後再重新啟動一次。

**Comment by 4860575** [comment]
> 如果 UNM 替換後還是顯示「無法播放」，請重新啟動 NeteaseMusic。如果還是不行，試試看清掉快取之後再重新啟動一次。

我是mac客户端。刚刚pull了。现在kuwo源可以了（仅测试了周董的部分歌曲）。

**Comment by pan93412** [comment]
> > 如果 UNM 替換後還是顯示「無法播放」，請重新啟動 NeteaseMusic。如果還是不行，試試看清掉快取之後再重新啟動一次。
> 
> 我是mac客户端。刚刚pull了。现在kuwo源可以了（仅测试了周董的部分歌曲）。
> 以前“pyncmd”可以解锁flac。现在启用“ENABLE_FLAC=true”也不行了

@1715173329

**Comment by 1715173329** [comment]
I can confirm it works ;)

**Comment by 1715173329** [comment]
@pan93412 现在 youtube 音源好像要对应区域的解密函数来解密 signatureCipher，无法再跨区域使用同一个 sign 算法

**Comment by pan93412** [comment]
> @pan93412 现在 youtube 音源好像要对应区域的解密函数来解密 signatureCipher，无法再跨区域使用同一个 sign 算法

要不要直接用 Fei1Yang 的 API（或者是 yt-download）

**Comment by 1715173329** [comment]
> 要不要直接用 Fei1Yang 的 new implementation（或者是 yt-download）

我没有看到 fei1yang 的实现 emmm，yt-download 对移动设备并不一定友好
因为 youtube 的网页代码里面就内嵌了视频信息，直接 parse 倒是可以用 - see #187

**Comment by pan93412** [comment]
> > 要不要直接用 Fei1Yang 的 new implementation（或者是 yt-download）
> 
> 我没有看到 fei1yang 的实现 emmm，yt-download 那个简直就是 sh*t，在目前的架构下面会直接卡死 request 导致 timeout，还有一些其他的奇怪问题
> 因为 youtube 的网页代码里面就内嵌了视频信息，直接 parse 倒是可以用 - see #187

你說得是 `youtube-dl` 還是 `yt-download`？如果是前者的話，應該是不會卡住 event loop；後者的話我也不知道怎麼回事 😗

**Comment by 1715173329** [comment]
`youtube-dl` 倒是没问题，不过对于移动设备而言不太友好

**Comment by pan93412** [comment]
```
$  env DEVELOPMENT=true ENABLE_LOCAL_VIP=true node app.js -e https://music.163.com -s -p 8080:8081 -o youtube
WARNING: You are in the development mode of UnblockNeteaseMusic.
WARNING: If you are a normal user, it is better to disable DEVELOPMENT mode by
WARNING:     DEVELOPMENT=false node app.js <your args>
WARNING: If you are a power user or a developer, when you encountered the 
WARNING:      Error: Cannot find module"
WARNING: issues, please install the dependencies with yarn first.
INFO: (app) HTTP Server running @ http://0.0.0.0:8080
INFO: (app) HTTPS Server running @ http://0.0.0.0:8081
INFO: (provider/match) Replaced: [33955999] 魔法少女チノ
    audioId: 33955999
    songName: "魔法少女チノ"
    url: "省略"
```

此外你的新版本能運作了（雖然沒修好 neteasemusic 在播放 YouTube aac 時的問題）

**Comment by 1715173329** [comment]
> 此外你的新版本能運作了（雖然沒修好 macOS 版 NeteaseMusic 在播放 YouTube aac 時的問題）

大概可能得按需调整了吧，macOS 版支持 webm 格式的音频吗？

**Comment by pan93412** [comment]
新版已修正。

**Comment by 1715173329** [comment]
`yt-download` 并不支持分片下载，它里面的 content-length 就直接等于整个文件大小，然后被 reject（
https://github.com/UnblockNeteaseMusic/server/blob/4acf168edc8657679e4446b6292867e86b86b3f4/src/provider/match.js#L150-L153

**Comment by 1715173329** [comment]
@pan93412 可以设置直接不检查 `yt-download` 的 content-length 吗？我这样测试可行

**Comment by pan93412** [comment]
> @pan93412 可以设置直接不检查 `yt-download` 的 content-length 吗？我这样测试可行

或許可以。但我不知道這個 code 存在的意義是什麼。

**Comment by 1715173329** [comment]
> 或許可以。但我不知道這個 code 存在的意義是什麼。

me too ;(
