### ISSUE TITLE
启用ENABLE_LOCAL_VIP后有什么区别？

### ISSUE THREAD

**Issue by byludy** [UnblockNeteaseMusic/server#180]
变量里面加了export ENABLE_LOCAL_VIP=true
但是电脑或者手机都没看出有区别啊

很多功能都没有对应的截图以及具体的
能不能都提供一下说明

**Comment by byludy** [comment]
![image](https://user-images.githubusercontent.com/56289598/133982181-b7f9e4fc-ba1f-41b4-94ce-7190372c6418.png)

**Comment by 4860575** [comment]
> 变量里面加了export ENABLE_LOCAL_VIP=true
> 但是电脑或者手机都没看出有区别啊
> 
> 很多功能都没有对应的截图以及具体的
> 能不能都提供一下说明

试试音效……

**Comment by pan93412** [comment]
可以在本地端啟用黑膠的功能。詳情見下圖。不過，這個 Local VIP 不能用來解鎖無損音質，也似乎也不支援網頁端。

## Before

<img width="317" alt="截圖 2021-09-20 下午7 49 12" src="https://user-images.githubusercontent.com/28441561/133997509-18f529c0-8a65-493f-aac2-f10c4a2971df.png">

## After

<img width="316" alt="截圖 2021-09-20 下午7 50 33" src="https://user-images.githubusercontent.com/28441561/133997552-61c23c5b-1763-4bb6-ae9b-46d8ca1602ed.png">
