### ISSUE TITLE
注册windows服务失败，提示"Error: Cannot find module 'node-windows'"

### ISSUE THREAD

**Issue by shz42** [UnblockNeteaseMusic/server#186]
尝试运行node nw.js注册windows服务，提示"Error: Cannot find module 'node-windows'"，是需要安装什么组件吗。
nodejs版本: v16.8.0
![图片](https://user-images.githubusercontent.com/63167402/134100674-0d882f9c-077a-4f44-bff7-07e329221113.png)

**Comment by 1715173329** [comment]
plz run `yarn` firstly...

**Comment by pan93412** [comment]
> 尝试运行node nw.js注册windows服务，提示"Error: Cannot find module 'node-windows'"，是需要安装什么组件吗。
> nodejs版本: v16.8.0
> ![图片](https://user-images.githubusercontent.com/63167402/134100674-0d882f9c-077a-4f44-bff7-07e329221113.png)

需要先安裝 yarn 才能執行這個命令。

**Comment by shz42** [comment]
> 
> 
> > 尝试运行node nw.js注册windows服务，提示"Error: Cannot find module 'node-windows'"，是需要安装什么组件吗。
> > nodejs版本: v16.8.0
> > ![图片](https://user-images.githubusercontent.com/63167402/134100674-0d882f9c-077a-4f44-bff7-07e329221113.png)
> 
> 需要先用 `yarn` 安裝 dependencies 之後才能執行這個命令。

安装之后可以运行了，感谢

**Comment by ttttya** [comment]
> 

大佬 能讲清楚点吗 怎么安装啊

**Comment by tjuyyz** [comment]
try  "npm link node-windows"
