### ISSUE TITLE
ubuntu centos debian 一键部署脚本

### ISSUE THREAD

**Issue by byludy** [UnblockNeteaseMusic/server#192]
原项目已经pull更新，所以改为原项目地址
`wget -N --no-check-certificate https://raw.githubusercontent.com/XIU2/Shell/master/unblock163.sh && chmod +x unblock163.sh && bash unblock163.sh`

文件位置

安装目录：/usr/local/UnblockNeteaseMusic

日志文件：/usr/local/UnblockNeteaseMusic/UnblockNeteaseMusic.log

其他命令

除了用脚本启动、停止、重启以外，还能通过其他命令操作。

启动：/etc/init.d/unblock163 start

停止：/etc/init.d/unblock163 stop

重启：/etc/init.d/unblock163 restart

查看状态：/etc/init.d/unblock163 status

要设置环境变量，可以编辑/etc/init.d/unblock163，在里面增加你需要的变量，如

export ENABLE_FLAC=true

export ENABLE_LOCAL_VIP=true

export LOG_LEVEL=debug

**Comment by pan93412** [comment]
準備遷移至 https://github.com/UnblockNeteaseMusic/linux-deploy-script

更多資訊，請查閱 #193
