### ISSUE TITLE
無法使用 B 站音源

### ISSUE THREAD

**Issue by xiaonuonuo** [UnblockNeteaseMusic/server#194]
## 版本

```
Author: Tianling Shen <i@cnsztl.eu.org>
Date:   Tue Sep 21 11:48:51 2021 +0800

    feat(ci): ignore bundle updates [skip ci]
    
    Signed-off-by: Tianling Shen <i@cnsztl.eu.org>

commit 5a4ff69727d5523767cfcd804b2456594e5767c3
```

## 代理方式

Hosts

**Comment by pan93412** [comment]
我昨天還能用啊？@1715173329 你可以幫我 check 一下嗎？謝謝！

**Comment by 1715173329** [comment]
如果你想要浏览器能够正常打开，则需要手动设定正确的 headers。
如果你只使用网易云音乐，UNM 会为你自动附上，

**Comment by xiaonuonuo** [comment]
正是网易云播放不了，所以我才把链接放到浏览器里面去试了一下，显示403

**Comment by xiaonuonuo** [comment]
![image](https://user-images.githubusercontent.com/18443078/134325564-42345eab-b6d4-4372-a3ba-1fe50fee35e8.png)

**Comment by xiaonuonuo** [comment]
@1715173329 @pan93412

**Comment by pan93412** [comment]
你仔細看一下下面的 url⋯⋯跟 bilibili 一點關係都沒有喔

如果不能播放，我猜你是 macOS 的 NeteaseMusic
把快取清掉之後 Command-Q 重新啟動

**Comment by pan93412** [comment]
關於 timeout 你先看一下 #173。簡而言之，跟 B 站無關。

**Comment by pan93412** [comment]
<img width="730" alt="截圖 2021-09-22 下午6 19 17" src="https://user-images.githubusercontent.com/28441561/134326470-555c18f3-a0a7-41cb-a2c1-0086b9e8d0f7.png">

我這裡確實可以播放。

<img width="1440" alt="截圖 2021-09-22 下午6 19 47" src="https://user-images.githubusercontent.com/28441561/134326551-a0741943-b091-4747-973f-43ace0bf75f6.png">

進來也是 403，印證 @1715173329 的解釋。

**Comment by xiaonuonuo** [comment]
咦，为什么你的网易云可以播放这个链接，我这边的直接就卡着不动了。
@pan93412

**Comment by pan93412** [comment]
> 咦，为什么你的网易云可以播放这个链接，我这边的直接就卡着不动了。
> @pan93412

1. 你使用的 UnblockNeteaseMusic 是哪個提交？
2. 你使用什麼方式設定 UNM (Proxy 還是 Hosts)

**Comment by xiaonuonuo** [comment]
> > 咦，为什么你的网易云可以播放这个链接，我这边的直接就卡着不动了。
> > @pan93412
> 
> 1. 你使用的 UnblockNeteaseMusic 是哪個提交？
> 2. 你使用什麼方式設定 UNM (Proxy 還是 Hosts)

你使用什麼方式設定 UNM (Proxy 還是 Hosts)
--------
Hosts

---------------------------------------------------------
你使用的 UnblockNeteaseMusic 是哪個提交？
-----
用的应该是最新的
`Author: Tianling Shen <i@cnsztl.eu.org>
Date:   Tue Sep 21 11:48:51 2021 +0800

    feat(ci): ignore bundle updates [skip ci]
    
    Signed-off-by: Tianling Shen <i@cnsztl.eu.org>

commit 5a4ff69727d5523767cfcd804b2456594e5767c3`

**Comment by xiaonuonuo** [comment]
> > 咦，为什么你的网易云可以播放这个链接，我这边的直接就卡着不动了。
> > @pan93412
> 
> 1. 你使用的 UnblockNeteaseMusic 是哪個提交？
> 2. 你使用什麼方式設定 UNM (Proxy 還是 Hosts)

host拦截 + 命令`node app.js -p 80 -f 59.111.160.197`

**Comment by xiaonuonuo** [comment]
so how to fix it?

**Comment by xiaonuonuo** [comment]
@pan93412

**Comment by pan93412** [comment]
> so how to fix it?

不太確定⋯⋯我先標 help wanted?

**Comment by xiaonuonuo** [comment]
对了，你说的快取清掉这个是什么意思？是指NeteaseMusic的缓存么

**Comment by pan93412** [comment]
<img width="690" alt="截圖 2021-09-22 下午11 08 21" src="https://user-images.githubusercontent.com/28441561/134370183-a94d2075-b124-45b4-afc5-af0db1f1d240.png">

**Comment by xiaonuonuo** [comment]
所以是清除缓存？

**Comment by pan93412** [comment]
嗯

**Comment by xiaonuonuo** [comment]
OK。随便问下，当前你的Mac OS客户端NeteaseMusic的版本可否发一下

**Comment by zzz6839** [comment]
windows的表示可以用B站音源，内核版本最新5a4ff69727d5523767cfcd804b2456594e5767c3，但是B站的音源会有不准确的，许嵩的“情侣装”，会被B站其他个人版本的替换

**Comment by 1715173329** [comment]
#195

For macOS:
- 信任证书
- 监听 80/443 
- 设置 endpoint（如果仍不工作）
