### ISSUE TITLE
无法解锁VIP歌曲

### ISSUE THREAD

**Issue by CaesarTheFoxxxx** [UnblockNeteaseMusic/server#218]
灰色歌曲可以解锁，可以在界面看到找寻其他音源。 VIP歌曲不查找其他音源直接进入试听。 是不支持解锁VIP还是我设置有问题？

**Comment by pan93412** [comment]
> 灰色歌曲可以解锁，可以在界面看到找寻其他音源。 VIP歌曲不查找其他音源直接进入试听。 是不支持解锁VIP还是我设置有问题？

1. 你使用的 NeteaseMusic 是什麼平台上的什麼版本？
2. 你 UnblockNeteaseMusic 用得是哪個 commit 構建版本？
3. 你是改 hosts、proxy 還是第三方工具 (如 Xposed)？
4. 你有配置其他項目嗎？

我昨天使用一切正常。
