### ISSUE TITLE
commit:50dae64fcfb17cb08d6924e6d123a67391b69b6e 提示“Error: Missing `pino-pretty` module”

### ISSUE THREAD

**Issue by 4860575** [UnblockNeteaseMusic/server#226]
系统：ubuntu20
node：v14.17.4
commit:50dae64fcfb17cb08d6924e6d123a67391b69b6e
启动方式：MIN_BR=320000 ENABLE_LOCAL_VIP=true node /root/UnblockNeteaseMusic/app.js -p 6200:6201 -o pyncmd kuwo -s >>/tmp/mp3.log 2>&1 &
试着安装 npm install -g pino-pretty
/usr/bin/pino-pretty -> /usr/lib/node_modules/pino-pretty/bin.js
+ pino-pretty@7.0.1
added 32 packages from 28 contributors in 1.54s
错误日志：

 

> /root/UnblockNeteaseMusic/precompiled/app.js:4481
>       throw Error('Missing `pino-pretty` module: `pino-pretty` must be installed separately');
> Error: Missing `pino-pretty` module: `pino-pretty` must be installed separately
>     at getPrettyStream (/root/UnblockNeteaseMusic/precompiled/app.js:4481:13)
>     at normalizeArgs (/root/UnblockNeteaseMusic/precompiled/app.js:4671:16)
>     at pino$1 (/root/UnblockNeteaseMusic/precompiled/app.js:5447:7)
>     at Object.<anonymous> (/root/UnblockNeteaseMusic/precompiled/app.js:5614:18)
>     at Module._compile (internal/modules/cjs/loader.js:1072:14)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
>     at Module.load (internal/modules/cjs/loader.js:937:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
>     at Module.require (internal/modules/cjs/loader.js:961:19)
>     at require (internal/modules/cjs/helpers.js:92:18)

**Comment by 1715173329** [comment]
fixed in the latest git commit.
