### ISSUE TITLE
更新后内置脚本出现了问题

### ISSUE THREAD

**Issue by luoxingran** [UnblockNeteaseMusic/server#250]
![Screenshot_20211009_215137_com netease cloudmusic](https://user-images.githubusercontent.com/83531505/136660987-259ecac8-e1ac-4ddb-a9eb-f894f0c9d116.jpg)

由于是内置脚本没法抓log只能发软件出来了，希望打咯能看看，10月1日的脚本都还是可以用的
https://qimoxue.lanzoui.com/ijzXsv5988b

**Comment by luoxingran** [comment]
![Uploading Screenshot_20211009_215929_com.vmos.pro.jpg…]()

**Comment by luoxingran** [comment]
![Screenshot_20211009_215929_com vmos pro](https://user-images.githubusercontent.com/83531505/136661063-c22a114d-19ff-4de3-9e76-6c6a95a32096.jpg)

**Comment by 1715173329** [comment]
。。？我建议去问软件作者
