### ISSUE TITLE
Docker 出现 Please check the availability of match sources.

### ISSUE THREAD

**Issue by kikozz** [UnblockNeteaseMusic/server#266]
用docker compose 和 镜像 都出现这个

**Comment by pan93412** [comment]
哪一個 tag

**Comment by pan93412** [comment]
問題有重現成功。我檢查一下

**Comment by pan93412** [comment]
561a7ec9a13404f4a877ffbbeb76c0a2222fb4ca 已修正本問題。

**Comment by kikozz** [comment]
> [561a7ec](https://github.com/UnblockNeteaseMusic/server/commit/561a7ec9a13404f4a877ffbbeb76c0a2222fb4ca) 已修正本問題。引入本問題的提交是 [e71fa56](https://github.com/UnblockNeteaseMusic/server/commit/e71fa56795a47ba3b89820e524ebf870eaeaccdf) 。
> 
> 這個 workflow 應已 push 最新修正到 `latest`。假如您測試上沒有問題，我就打個 tag 更新 `release` 的版本：https://github.com/UnblockNeteaseMusic/server/runs/3914848030

latest 和 release 目前都是这样  我又特地去重新下载了镜像试过了.. Docker Hub已显示更新 可我重新应用镜像后还是同样的问题

**Comment by kikozz** [comment]
> 試試看 `docker pull pan93412/unblock-netease-music-enhanced` 之後重新執行？

thx 重新 pull 后正常了
