### ISSUE TITLE
pyncmd无法使用

### ISSUE THREAD

**Issue by 4860575** [UnblockNeteaseMusic/server#313]
git commit b38502d288401becedfc506d0340fe8a1c8102d5 (HEAD, origin/enhanced, origin/HEAD)
环境：ubuntu 20.04
node：v14.18.1
启动方式：MIN_BR=320000 ENABLE_LOCAL_VIP=true node /home/G/UnblockNeteaseMusic/app.js -o pyncmd -p 6200:6201
日志如下：
INFO: (app) HTTP Server running @ http://0.0.0.0:6200
INFO: (app) HTTPS Server running @ http://0.0.0.0:6201
ERROR: (provider/match) unable to verify the first certificate
    Error: unable to verify the first certificate
        at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)
        at TLSSocket.emit (events.js:400:28)
        at TLSSocket._finishInit (_tls_wrap.js:937:8)
        at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12)
    code: UNABLE_TO_VERIFY_LEAF_SIGNATURE
ERROR: (hook) No one promise resolved
    AggregateError: No one promise resolved
        at /home/G/UnblockNeteaseMusic/precompiled/app.js:13723:43
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
ERROR: (provider/match) unable to verify the first certificate
    Error: unable to verify the first certificate
        at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)
        at TLSSocket.emit (events.js:400:28)
        at TLSSocket._finishInit (_tls_wrap.js:937:8)
        at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12)
    code: UNABLE_TO_VERIFY_LEAF_SIGNATURE
ERROR: (hook) No one promise resolved
    AggregateError: No one promise resolved
        at /home/G/UnblockNeteaseMusic/precompiled/app.js:13723:43
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
ERROR: (provider/match) unable to verify the first certificate
    Error: unable to verify the first certificate
        at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)
        at TLSSocket.emit (events.js:400:28)
        at TLSSocket._finishInit (_tls_wrap.js:937:8)
        at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12)
    code: UNABLE_TO_VERIFY_LEAF_SIGNATURE
ERROR: (hook) No one promise resolved
    AggregateError: No one promise resolved
        at /home/G/UnblockNeteaseMusic/precompiled/app.js:13723:43
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
ERROR: (provider/match) unable to verify the first certificate
    Error: unable to verify the first certificate
        at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)
        at TLSSocket.emit (events.js:400:28)
        at TLSSocket._finishInit (_tls_wrap.js:937:8)
        at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12)
    code: UNABLE_TO_VERIFY_LEAF_SIGNATURE
ERROR: (hook) No one promise resolved
    AggregateError: No one promise resolved
        at /home/G/UnblockNeteaseMusic/precompiled/app.js:13723:43
        at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by 1715173329** [comment]
This API was down.

**Comment by gy18505** [comment]
is there anyone who handled this problem?

**Comment by 1715173329** [comment]
> is there anyone who handled this problem?

This is a upstream issue, so we cannot fix it.

**Comment by 4860575** [comment]
这个api应该是正常的测试方式如下：
使用歌曲ID“ 29732235”
https://mos9527.tooo.top/ncm/pyncm/track/GetTrackAudio?song_ids= 29732235
得到返回“{"data": [{"id": 29732235, "url": "http://m7.music.126.net/20211207213258/da90fc3012f77e75273f7c22b2e8b419/ymusic/227e/246e/981c/25f2b54d3bcd035be691fc52311f5ea6.mp3", "br": 320000, "size": 13075897, "md5": "25f2b54d3bcd035be691fc52311f5ea6", "code": 200, "expi": 1200, "type": "mp3", "gain": 0.0, "fee": 8, "uf": null, "payed": 1, "flag": 4, "canExtend": false, "freeTrialInfo": null, "level": "exhigh", "encodeType": "mp3", "freeTrialPrivilege": {"resConsumable": false, "userConsumable": false}, "freeTimeTrialPrivilege": {"resConsumable": false, "userConsumable": false, "type": 0, "remainTime": 0}, "urlSource": 0}], "code": 200}”

**Comment by 1715173329** [comment]
Only found "CONNECTION REFUSED".
Maybe its fullchain is broken, I have no idea. We have degraded to http already.

**Comment by 4860575** [comment]
> Only found "CONNECTION REFUSED".
> Maybe its fullchain is broken, I have no idea. We have degraded to http already.

但是访问 https://mos9527.tooo.top/ncm/ 是可以正常搜索歌曲并播放的

**Comment by pan93412** [comment]
> > Only found "CONNECTION REFUSED".
> > Maybe its fullchain is broken, I have no idea. We have degraded to http already.
> 
> 但是访问 https://mos9527.tooo.top/ncm/ 是可以正常搜索歌曲并播放的

主要是我們開發者端沒辦法存取這個 API :-( 老實說我們也不知道怎麼修一個連不上的 API

<img width="842" alt="截圖 2021-12-07 下午11 28 16" src="https://user-images.githubusercontent.com/28441561/145057832-89fd1946-3e26-418c-a400-ffe1e9193d12.png">

**Comment by 1715173329** [comment]
刚才总算是能连上了，近期看看是什么情况。

**Comment by 1715173329** [comment]
这个 api 缺少中间证书，证书链不完整，所以 Node.js 无法验证其有效性。
现在上游启用了强制 https，无法绕过。

**Comment by a6513375** [comment]
试着修了下 #441 441

**Comment by 1715173329** [comment]
workaround #441 #447
