### ISSUE TITLE
ytdlp 音源调用时报错

### ISSUE THREAD

**Issue by EdisonJwa** [UnblockNeteaseMusic/server#323]
报错代码如下（不是网络问题，手动调用时可以正常返回数据）

```
ERROR: (hook) Promise.any is not a function
    TypeError: Promise.any is not a function
        at match (/root/UnblockNeteaseMusic-fork/src/provider/match.js:64:34)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
        at async Promise.all (index 0)
INFO: (spawn) running yt-dlp -f 140 --dump-json ytsearch1:하나뿐인 사람 - K.Will
(node:3338) UnhandledPromiseRejectionWarning: undefined
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3338) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3338) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
INFO: (spawn) running yt-dlp -f 140 --dump-json https://www.youtube.com/watch?v=ug1kMvF1pKY
WARN: (request) The request timed out, or the requester didn't handle the response.
```

**Comment by pan93412** [comment]
> 报错代码如下（不是网络问题，手动调用时可以正常返回数据）
> 
> ```
> ERROR: (hook) Promise.any is not a function
>     TypeError: Promise.any is not a function
>         at match (/root/UnblockNeteaseMusic-fork/src/provider/match.js:64:34)
>         at processTicksAndRejections (internal/process/task_queues.js:95:5)
>         at async Promise.all (index 0)
> INFO: (spawn) running yt-dlp -f 140 --dump-json ytsearch1:하나뿐인 사람 - K.Will
> (node:3338) UnhandledPromiseRejectionWarning: undefined
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:3338) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> (node:3338) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> INFO: (spawn) running yt-dlp -f 140 --dump-json https://www.youtube.com/watch?v=ug1kMvF1pKY
> WARN: (request) The request timed out, or the requester didn't handle the response.
> ```

升級成 Node.js 16 以上版本，或者是改用 precompiled 版本（直接啟動根目錄的 `app.js`）。
