### ISSUE TITLE
UWP无法使用

### ISSUE THREAD

**Issue by Duan-rax** [UnblockNeteaseMusic/server#325]
使用glider 将http代理端口转为ss服务，并成功在安卓和ios上使用

启动命令：pm2 restart app.js --name="UnblockNeteaseMusic" -- -s -p 18123:18125 -o kuwo -e https://music.163.com

日志：|UnblockNeteaseMusic  | [418602085] 英雄
0|UnblockNeteaseMusic  | http://other.player.rh01.sycdn.kuwo.cn/e78468fd323ef59f16a2d0ac731efb49/619133a6/resource/n2/27/63/2871808815.mp3
0|UnblockNeteaseMusic  | TUNNEL > localhost:18125
0|UnblockNeteaseMusic  | TUNNEL > localhost:18125
0|UnblockNeteaseMusic  | TUNNEL > localhost:18125
0|UnblockNeteaseMusic  | TUNNEL > localhost:18125
0|UnblockNeteaseMusic  | TUNNEL > localhost:18125
0|UnblockNeteaseMusic  | TUNNEL > localhost:18125
0|UnblockNeteaseMusic  | TUNNEL > clientlog.music.163.com:443
0|UnblockNeteaseMusic  | TUNNEL > localhost:18125
0|UnblockNeteaseMusic  | TUNNEL > localhost:18125
0|UnblockNeteaseMusic  | TUNNEL > localhost:18125

**Comment by 1715173329** [comment]
Let's move to discussion.
