### ISSUE TITLE
pyncmd无法调用，提示证书校验失败

### ISSUE THREAD

**Issue by gy18505** [UnblockNeteaseMusic/server#364]
通过error catcher可获知以下异常：
```
 Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1088:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket._finishInit (_tls_wrap.js:666:8) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
```
这个问题有解决思路吗？求解~

**Comment by 1715173329** [comment]
pyncmd is down.
See #313

**Comment by gy18505** [comment]
> pyncmd is down. See #313

But why could I fetch the very data exactly needed by manually visiting(e.g. via browser)? The source url is still able to play... and I just can't figure it out why the script itself failed to work. I still believe there should be a similar way to handle like this, do u guys have any good idea?
