### ISSUE TITLE
Docker image: lack of dependencies and flexibility of configuration

### ISSUE THREAD

**Issue by TURX** [UnblockNeteaseMusic/server#383]
Although I can deploy my certificates through bind mounts, I noticed that I cannot use bind mounts to install youtube-dl and yt-dlp which are necessary for using YouTube as a source. I would suggest you include all third-party dependencies of the features into the docker image.

Also, for the China relay (国内中继) mentioned in 进阶配置, it is troublesome to configure within the Docker container (maybe lost after updates), and the program is precompiled that I cannot change directly in insure.js. It can be transformed into an optional command-line argument.

**Comment by pan93412** [comment]
Thanks for reminding! I'll add it later, or do you want to make a PR for it?

**Comment by pan93412** [comment]
May be fixed in 3a6244c75eb52ff9fde1397dfd549f27cb7bf3ab, and has pushed in 9d3dc3450f02be25922a155a0ae677f82c6fc59e
