### ISSUE TITLE
"bilibili" resolver can not cover every cases

### ISSUE THREAD

**Issue by TURX** [UnblockNeteaseMusic/server#389]
I have found that although the bilibili resolver can get a URL (under *.bilivideo.com, I do not know if it is correct), through my test, the response is always 403. If the URL is correct but the request fails the checks by bilibili, User-Agent, referrer, and something like the cookie from a user with the subscription is needed to retrieve FLAC and paid music might be considered to solve this problem.

Furthermore, as mentioned in issue #190, although yt-dlp can return the correct URL of an audio file and work well on Windows and Chrome, the macOS Netease Music client can only play the initial 9 seconds. It seems that youtube-dl may also have this issue, but I have not confirmed it strictly. There can be an option (but not required) to convert the format that is fully supported by the client.

**Addition**: For bilibili, I can see 403 for the media requested in Chrome. Also, The macOS client cannot start playing the media; instead, it would get stuck.

**Comment by TURX** [comment]
I have tested the solutions. I found I can get the audio file only by the following command:
```
curl "http://upos-sz-mirrorks3.bilivideo.com/..." -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" -H "referer: https://bilibili.com"
```
It seems that both valid user-agent and referer are required, otherwise there should be a 403 error.

However, the current server cannot handle user-agent and referer, because it just sends out the URL without caching the file while it is impossible to change the client. I suggest the feasible solution to cache the file that the client can access it by another port through HTTP(s). This feature seems also to be required by transcoding like for YouTube music.

**Comment by TURX** [comment]
I also find a typo here:
https://github.com/UnblockNeteaseMusic/server/blob/577fd85a45bee7e456eb02d3fc40172fe75000b0/src/provider/bilibili.js#L35

```rivilege``` should be ```privilege```

**Comment by pan93412** [comment]
> I also find a typo here:
> 
> https://github.com/UnblockNeteaseMusic/server/blob/577fd85a45bee7e456eb02d3fc40172fe75000b0/src/provider/bilibili.js#L35
> 
> `rivilege` should be `privilege`
> 
> And the `quality` does not need to be limited to `2` (320 Kbps for anonymous user), it can be `3` (lossless for subscribers) in case the user provides bilibili API token or cookie with a valid subscription.
> 
> https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/audio/musicstream_url.md#%E8%8E%B7%E5%8F%96%E9%9F%B3%E9%A2%91%E6%B5%81URL%EF%BC%88%E5%8F%AF%E8%8E%B7%E5%8F%96%E4%BB%98%E8%B4%B9%E9%9F%B3%E9%A2%91%EF%BC%89%EF%BC%88%E5%8F%8C%E7%AB%AF%EF%BC%89

I'll investigate it later. Thanks for telling me this! ❤️

**Comment by 1715173329** [comment]
> However, the current server cannot handle user-agent and referer, because it just sends out the URL without caching the file while it is impossible to change the client.

https://github.com/UnblockNeteaseMusic/server/blob/52c4702eb7a85b1f3f8c7e234f8828a58515a5a0/src/server.js#L130-L133
It works for me.

**Comment by TURX** [comment]
> > However, the current server cannot handle user-agent and referer, because it just sends out the URL without caching the file while it is impossible to change the client.
> 
> https://github.com/UnblockNeteaseMusic/server/blob/52c4702eb7a85b1f3f8c7e234f8828a58515a5a0/src/server.js#L130-L133
> 
> 
> It works for me.

I think this header tweak works for getting the correct URL of the audio file from a search query, but the issue is that the music client cannot pass the correct user-agent and referer to play the audio file.

**Comment by pan93412** [comment]
> > > However, the current server cannot handle user-agent and referer, because it just sends out the URL without caching the file while it is impossible to change the client.
> > 
> > 
> > https://github.com/UnblockNeteaseMusic/server/blob/52c4702eb7a85b1f3f8c7e234f8828a58515a5a0/src/server.js#L130-L133
> > 
> > It works for me.
> 
> I think this header tweak works for getting the correct URL of the audio file from a search query, but the issue is that the music client cannot pass the correct user-agent and referer to play the audio file.

I will work on writing a new generation of UnblockNeteaseMusic. Maybe it will be resolved naturally (since it fetches music from our server instead of the remote source directly)

**Comment by 1715173329** [comment]
> I think this header tweak works for getting the correct URL of the audio file from a search query.

Not really, this a MitM attack for client.
You won't need any specific headers when query information.
