### ISSUE TITLE
新版安卓无法使用

### ISSUE THREAD

**Issue by LastStranger** [UnblockNeteaseMusic/server#429]
v8.6.50安卓版本不可用,提示网络异常

**Comment by pan93412** [comment]
#427 或許對你有幫助？

**Comment by LastStranger** [comment]
> 

没有帮助,新版的安卓要装证书吗?

**Comment by pan93412** [comment]
既然沒幫助，那應該就是 Android 的改版問題了。

**Comment by 1582421598** [comment]
尝试配合杜比大喇叭一起使用？我在关闭杜比大喇叭的情况下也未能复现你的问题。
补充：WIFI-代理-127.0.0.1:23331，node app.js -p 23331:23332 -o pyncmd kuwo qq bilibili youtube

**Comment by RManLuo** [comment]
> 尝试配合杜比大喇叭一起使用？我在关闭杜比大喇叭的情况下也未能复现你的问题。 补充：WIFI-代理-127.0.0.1:23331，node app.js -p 23331:23332 -o pyncmd kuwo qq bilibili youtube

请问杜比大喇叭该如何配置呢？

**Comment by RManLuo** [comment]
网易云音乐v8.6.60，配合Clash 全局代理网易云音乐流量，测试通过，未安装证书。服务端命令参考：
```
docker run  -d -p 8080:8080 -e ENABLE_FLAC=true -e NODE_ENV=production --restart=always --log-opt max-size=10m --name=music pan93412/unblock-netease-music-enhanced -e https://music.163.com
```

**Comment by 1582421598** [comment]
> > 尝试配合杜比大喇叭一起使用？我在关闭杜比大喇叭的情况下也未能复现你的问题。 补充：WIFI-代理-127.0.0.1:23331，node app.js -p 23331:23332 -o pyncmd kuwo qq bilibili youtube
> 
> 请问杜比大喇叭该如何配置呢？

安装杜比大喇叭，然后任意XPOSED框架里启用他，选作用域应该就可以。如果感觉它里面的unblockneteasemusic模块版本低，可以用MT管理器对其进行替换，之后重签名即可。如果是自己有解锁用服务器。杜比大喇叭最新版可以自定义解锁服务器(不知道发release了没，不过源码里已经写了)

**Comment by RManLuo** [comment]
> @RManLuo 有Clash的完整的配置文件看看吗？谢谢了

这个项目会对您有帮助：https://github.com/DesperadoJ/Rules-for-UnblockNeteaseMusic
