### ISSUE TITLE
希望添加支持命令行控制本地黑胶的开关

### ISSUE THREAD

**Issue by a6513375** [UnblockNeteaseMusic/server#442]
如题

**Comment by 1715173329** [comment]
... but why?

**Comment by a6513375** [comment]
我就只是提个建议XDD

**Comment by pan93412** [comment]
其實實作這個有點困難⋯⋯ UNM 並不是一套 CLI 軟體。

**Comment by a6513375** [comment]
> 其實實作這個有點困難⋯⋯ UNM 並不是 TUI 軟體。

好
看下我的pr( #441

**Comment by pan93412** [comment]
> > 其實實作這個有點困難⋯⋯ UNM 並不是 TUI 軟體。
> 
> 好 看下我的pr( #441

已經看到了，但我在重構 UNM。晚點我會手動合併。
