### ISSUE TITLE
windows客户端一起听功能失效

### ISSUE THREAD

**Issue by WuliangHuang** [UnblockNeteaseMusic/server#457]
您好，我注意到在#316和#319中提到增加了一起听功能的支持，但是在网易云windows客户端2.9.6版本，使用服务器部署目前最新版v0.27.0-rc.4 ，网易云设置代理为服务器的地址的情况下，一起听功能是无法使用的。
相关的情况在于：
1. 具体在于直接邀请，邀请的信息在消息中不存在，双方也无法收到关于邀请的消息。
2. 通过邀请链接进行分享时，正常的邀请链接应该例如https://st.music.163.com/listen-together/share/?songId=..&roomId=..&inviterId=..， 但是在使用代理后邀请链接省略了前面的地址，直接为/listen-together/share/?songId=..&roomId=..&inviterId=..

我想了解这可能是什么原因造成的。谢谢作者。

**Comment by 1582421598** [comment]
所以网易云音乐windows客户端的一起听是可以正常使用的？我自己在测试中，关闭了代理，但是一起听是无法与手机客户端进行同步的，但是手机端与手机端可以正常同步(启用代理的情况下)。

**Comment by 1715173329** [comment]
使用最新的提交 + 2.10.5 测试正常，更新下本项目试试

**Comment by 1715173329** [comment]
stale, closing.
