### ISSUE TITLE
pyncmd是不是彻底挂了

### ISSUE THREAD

**Issue by ssrubsd** [UnblockNeteaseMusic/server#522]
打开https://mos9527.tooo.top/ncm/ 居然会跳转到gov.cn，但https://mos9527.tooo.top 是正常访问的

而且现在即便是最新版选择pyncmd音源也一样是不能用

**Comment by pan93412** [comment]
我們好像已經換掉 pyncmd 音源的伺服器了。你可以試試看最新 master 分支的版本。

**Comment by ssrubsd** [comment]
> 我們好像已經換掉 pyncmd 音源的伺服器了。你可以試試看最新 master 分支的版本。

我指的就是最新的源码，而且使用[a6513375](https://github.com/UnblockNeteaseMusic/server/commit/9b73cf919bc839c31942e5b9622237f7acc98b9a)所提供的反代服务一样会跳转到gov.cn
例子：https://service-q3dhb0bw-1302373778.gz.apigw.tencentcs.com/pyncm/track/GetTrackAudio?song_ids=26349641&bitrate=320000
pyncmd 作者所搭建的https://greats3an.github.io/pyncmd/ 并没有此类问题
