### ISSUE TITLE
qq源好像无法使用

### ISSUE THREAD

**Issue by ls148478** [UnblockNeteaseMusic/server#566]
已添加ck 但是一直提示被拒绝
搜了下Issues 貌似没有解决方案
`DEBUG: (provider/match) Getting the audio...
    source: "qq"
    info: {
      "name": "布拉格广场",
      "id": 400162703,
      "alias": [],
      "duration": 291709,
      "album": {
        "name": "爱舞炫 盛装舞曲精选",
        "id": 34429091
      },
      "artists": [
        {
          "name": "蔡依林",
          "id": 7219
        },
        {
          "name": "周杰伦",
          "id": 6452
        }
      ],
      "keyword": "布拉格广场 - 蔡依林 / 周杰伦"
    }
DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "provider/qq"
DEBUG: (cache) Something did not hit. Storing the execution result...
    logKey: "Something"
    cacheStorageId: "provider/qq"
DEBUG: (request) Start requesting https://c.y.qq.com/soso/fcgi-bin/client_search_cp?ct=24&qqmusic_ver=1298&new_json=1&remoteplace=txt.yqq.center&t=0&aggr=1&cr=1&catZhida=1&lossless=0&flag_qc=0&p=1&n=20&w=%E5%B8%83%E6%8B%89%E6%A0%BC%E5%B9%BF%E5%9C%BA%20-%20%E8%94%A1%E4%BE%9D%E6%9E%97%20%2F%20%E5%91%A8%E6%9D%B0%E4%BC%A6&g_tk=5381&jsonpCallback=MusicJsonCallback10005317669353331&loginUin=0&hostUin=0&format=jsonp&inCharset=utf8&outCharset=utf-8&notice=0&platform=yqq&needNewCode=0
ERROR: (hook) All promises were rejected
    AggregateError: All promises were rejected
`

**Comment by 1715173329** [comment]
刚刚看了下现在 QQ 音乐连搜索都必须登录了，应该是需要附上对应的 cookie。

**Comment by 1715173329** [comment]
> 刚刚看了下现在 QQ 音乐连搜索都必须登录了，应该是需要附上对应的 cookie。

倒是我想多了，移除了一个有问题的参数后恢复正常。

**Comment by pan93412** [comment]
Fixed in [b640630](https://github.com/UnblockNeteaseMusic/server/commit/b6406308d66aef684c94bd5cd64bd6e1b68154fd).

**Comment by 1715173329** [comment]
@pan93412 似乎还有点问题

**Comment by ls148478** [comment]
感谢大佬 已成功
