### ISSUE TITLE
终端显示 CJK 字符乱码

### ISSUE THREAD

**Issue by FrzMtrsprt** [UnblockNeteaseMusic/server#569]
如图，歌名中含有 CJK 字符时，会显示乱码，命令提示符和 Windows Terminal 中均会出现此问题。

![WindowsTerminal_isthmd7p6O](https://user-images.githubusercontent.com/15852717/157228011-aad4f873-801c-4216-aa6d-54ec6e06146e.png)

（请忽略 yt-dlp 的报错

**Comment by pan93412** [comment]
這是 Windows 終端預設不支援 Unicode 編碼所致。應不屬於 UnblockNeteaseMusic 的問題。
