### ISSUE TITLE
kuwo，kugou，migu 必须使用 https

### ISSUE THREAD

**Issue by Creepercdn** [UnblockNeteaseMusic/server#590]
kuwo，kugou，migu 必须使用 https。（2022/3/20 更新）
但是，源码并未更新。
此外，migu 的 API 仍然会返回 http 的音频 URL，必须手动转为 https。（在 match.js 的 check() 中添加：
```js
if(url.slice(0,5)==='http:'){
    url = url.slice(0,4) + 's' + url.slice(4, -1);
}
```
此外，https://rr01.sycdn.kuwo.cn/ 使用了版本错误的协议。

**Comment by Creepercdn** [comment]
https://rr01.sycdn.kuwo.cn/ 错误为：
尚未正确验证从远程服务器收到的证书。错误代码是 0x80092013。TLS 连接请求失败。所附数据包含服务器证书。
创建 TLS 客户端 凭据时发生严重错误。内部错误状态为 10013。

**Comment by Creepercdn** [comment]
```
> openssl s_client -connect rr01.sycdn.kuwo.cn:443 -servername rr01.sycdn.kuwo.cn
CONNECTED(000001C0)
182D0000:error:0A000410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl\record\rec_layer_s3.c:1584:SSL alert number 40
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 324 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

**Comment by 1715173329** [comment]
> https://rr01.sycdn.kuwo.cn/ 错误为： 尚未正确验证从远程服务器收到的证书。错误代码是 0x80092013。TLS 连接请求失败。所附数据包含服务器证书。 创建 TLS 客户端 凭据时发生严重错误。内部错误状态为 10013。

只是不支持 https 罢了。

如果某些环境必须使用 https，例如 iOS 一类，设定 endpoint 即可 `-e https://music.163.com`

**Comment by Creepercdn** [comment]
http://rr01.sycdn.kuwo.cn/ 会连接超时。

**Comment by 1715173329** [comment]
> http://rr01.sycdn.kuwo.cn/ 会连接超时。

那是你网络问题。

**Comment by Creepercdn** [comment]
几天前无法访问。目前已经恢复。
