### ISSUE TITLE
ios代理模式不可用

### ISSUE THREAD

**Issue by xiegoudan** [UnblockNeteaseMusic/server#595]
之前提了在Android 的代理模式不可用问题，后面回答说在ios端使用可以支持最新版。
后经过测试，出现了如下问题：
在打开搜索列表页面时，还是显示试听：
![](https://s3.bmp.ovh/imgs/2022/03/f3f38b7bfffc58dd.jpg)
在打开我喜欢的页面时，却是可以正常显示：
![](https://s3.bmp.ovh/imgs/2022/03/62163a4f8c66025e.jpg)

如果点击试听的歌曲，正常情况下，只有一小段可以听，但是如果你拖动到那一小段后面只有就能正常听

配置如下图：
![](https://s3.bmp.ovh/imgs/2022/03/471098e389951f71.png)
![](https://s3.bmp.ovh/imgs/2022/03/5d5f40c6c25ad4aa.jpg)

**Comment by www6130911** [comment]
林俊杰好评

**Comment by 1715173329** [comment]
目前姑且算是解决了这个问题，搜索页中仍然提示“试听”或“无版权”，但已经可以正常点击并播放。
