### ISSUE TITLE
Android版网易云音乐使用问题

### ISSUE THREAD

**Issue by lyh20110** [UnblockNeteaseMusic/server#612]
您好，我在云服务器上使用exe文件进行部署，并且开放相应的端口以供外部访问，在Android手机上使用（通过数据网络并新建APN的方式），用周董的歌做测试，发现用网易云音乐极速版可以正常播放，而用最新的8.7.22版本提示无法找到资源，请问新版的是不支持吗？

**Comment by 1715173329** [comment]
不支持。如需在新版使用请配合 xposed 模块 https://github.com/nining377/dolby_beta

**Comment by lyh20110** [comment]
后续更新会支持新版吗？

**Comment by wukibaka** [comment]
> 不支持。如需在新版使用请配合 xposed 模块 https://github.com/nining377/dolby_beta

经测试 8.5.40以前还可以靠大喇叭 8.6.0以后大喇叭都失效了

**Comment by luoxingran** [comment]
> 不支持。如需在新版使用请配合 xposed 模块 https://github.com/nining377/dolby_beta

从8.6.0开始，通过clash代理方式发现网易云客户端
interface.music.163.com 并未通过代理脚本而是直接从网易云服务器返回数据

**Comment by Gyx200911** [comment]
所以说 安卓现在除了大喇叭之外无任何办法了？

**Comment by 1715173329** [comment]
Should be fixed now?

**Comment by Trytoz** [comment]
这是来自QQ邮箱的自动回复邮件。邮件我已收到。

**Comment by pikachullk** [comment]
我试了一下~酷安历史版本有8.3.0是可以用的~新版用不了了~暂时解决

**Comment by 1715173329** [comment]
Fixed.
