### ISSUE TITLE
注册为windows服务后无法使用

### ISSUE THREAD

**Issue by crassing** [UnblockNeteaseMusic/server#620]
无论是默认的端口还是自定义的都连不上网，
日志文件是：
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@author.io/args'
Require stack:
- D:\server-enhanced1\node_modules\node-windows\lib\wrapper.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\server-enhanced1\node_modules\node-windows\lib\wrapper.js:3:12)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\server-enhanced1\\node_modules\\node-windows\\lib\\wrapper.js'
  ]
}

**Comment by crassing** [comment]
是还缺少什么东西吗？

**Comment by crassing** [comment]
<img width="790" alt="屏幕截图 2022-04-05 160942" src="https://user-images.githubusercontent.com/34905210/161708787-2597d50d-ccd6-4ae4-8713-8cab6e75c630.png">

**Comment by eipip1e0** [comment]
[https://github.com/UnblockNeteaseMusic/server/issues/619](url)

**Comment by eipip1e0** [comment]
#619

**Comment by pan93412** [comment]
> 无论是默认的端口还是自定义的都连不上网， 日志文件是： node:internal/modules/cjs/loader:936 throw err; ^
> 
> Error: Cannot find module '@author.io/args' Require stack:
> 
> * D:\server-enhanced1\node_modules\node-windows\lib\wrapper.js
>   at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>   at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>   at Module.require (node:internal/modules/cjs/loader:1005:19)
>   at require (node:internal/modules/cjs/helpers:102:18)
>   at Object. (D:\server-enhanced1\node_modules\node-windows\lib\wrapper.js:3:12)
>   at Module._compile (node:internal/modules/cjs/loader:1103:14)
>   at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
>   at Module.load (node:internal/modules/cjs/loader:981:32)
>   at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>   at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>   'D:\server-enhanced1\node_modules\node-windows\lib\wrapper.js'
>   ]
>   }

試試看 `yarn && yarn node nw.js`

**Comment by maxelblack** [comment]
现在可以 `npm install node-windows@1.0.0-beta.6` 临时解决下

（坐等修bug中）

**Comment by zxa3256855565** [comment]
> 

谢谢，解决了

**Comment by catshitz** [comment]
> 现在可以 `npm install node-windows@1.0.0-beta.6` 临时解决下
> 
> （坐等修bug中）

可真不容易，教程久远，一堆漏洞，先安装npm & yarn没大写，node.js低版本老命令废弃装不上没提醒。兜兜转转查一圈issue才找到正确答案，一堆自以为问题解决的自行closed issue压根就不是有效答案。

**Comment by pan93412** [comment]
> > 现在可以 `npm install node-windows@1.0.0-beta.6` 临时解决下
> > （坐等修bug中）
> 
> 可真不容易，教程久远，一堆漏洞，先安装npm & yarn没大写，node.js低版本老命令废弃装不上没提醒。兜兜转转查一圈issue才找到正确答案，一堆自以为解决问题的人自行closed issue，搞半天压根就不是有效答案。

確實，整個專案有點像屎山，而且也沒有非常好的說明文件。

事實上 UNM 的 UX 和說明文件早已詬病許久，我和幾位開發者也知悉；然而這個專案的駕馭難度，連我自己都不見得可以掌握了——直至現在，我仍不能對各種功能瞭落指掌。

fork 之後我和團隊成員有對 codebase 進行改造，優化了一部分體驗；但這些終究是小打小鬧，我仍然沒有能力為 UX 做出更有用的改進。也因為考量到 UX 不佳以及維護上的難度，我其實有嘗試把 UNM 移植到 Rust 以及其他語言，順帶進行架構上的翻新，和文件上的補全。

不過中國音樂平台逐漸邁向正版、正規化，也開始在封殺 UNM 使用的 API。我已沒興趣繼續「貓捉老鼠」的遊戲（甚至我們還把「路徑」清楚畫在 GitHub 上了——就像是駭客把自己的漏洞公諸於世，廠商根本就不需要花心思「逆向」我們的做法），所以我已經轉到 Spotify 了。也因為轉到 Spotify 了，我更少維護 UNM 了——畢竟我日常生活也有些事情，所以 UNM 我一直沒有把他排在很高的優先級。

很抱歉讓你覺得這個專案毫無章法（事實上連我這個 maintainer 都不見得知道怎麼駕馭了）。如果你有興趣改進 UNM 的任何方面的話，很歡迎加入團隊，然後繼續讓 UNM 重回巔峰。
