### ISSUE TITLE
typeError: Promise.any is not a function\n 新鲜的BUG出炉了？

### ISSUE THREAD

**Issue by zzz6839** [UnblockNeteaseMusic/server#678]
Succeeded in updating core.
Current core version: e88d9ff99320399ea8554cc3f38a1b128a6bef4f.

{"level":30,"time":1652179160497,"pid":10442,"hostname":"OpenWrt","scope":"app","msg":"HTTP Server running @ http://0.0.0.0:5200"}
{"level":30,"time":1652179160499,"pid":10442,"hostname":"OpenWrt","scope":"app","msg":"HTTPS Server running @ http://0.0.0.0:5202"}
{"level":50,"time":1652179295416,"pid":10442,"hostname":"OpenWrt","scope":"hook","stack":"TypeError: Promise.any is not a function\n    at match (/usr/share/unblockneteasemusic/core/app.js:2441:37)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async Promise.all (index 0)","type":"Error","msg":"Promise.any is not a function"}
{"level":50,"time":1652179307160,"pid":10442,"hostname":"OpenWrt","scope":"hook","stack":"TypeError: Promise.any is not a function\n    at match (/usr/share/unblockneteasemusic/core/app.js:2441:37)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async Promise.all (index 0)","type":"Error","msg":"Promise.any is not a function"}
{"level":50,"time":1652179309951,"pid":10442,"hostname":"OpenWrt","scope":"hook","stack":"TypeError: Promise.any is not a function\n    at match (/usr/share/unblockneteasemusic/core/app.js:2441:37)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async Promise.all (index 0)","type":"Error","msg":"Promise.any is not a function"}
{"level":50,"time":1652179311906,"pid":10442,"hostname":"OpenWrt","scope":"hook","stack":"TypeError: Promise.any is not a function\n    at match (/usr/share/unblockneteasemusic/core/app.js:2441:37)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async Promise.all (index 0)","type":"Error","msg":"Promise.any is not a function"}
{"level":50,"time":1652179331931,"pid":10442,"hostname":"OpenWrt","scope":"hook","stack":"TypeError: Promise.any is not a function\n    at match (/usr/share/unblockneteasemusic/core/app.js:2441:37)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async Promise.all (index 0)","type":"Error","msg":"Promise.any is not a function"}

**Comment by 1715173329** [comment]
命令行执行 `unm-debug`，贴出日志链接。

**Comment by zzz6839** [comment]
https://transfer.sh/QwglSA/unm-debugging-output.txt
@1715173329

**Comment by 1715173329** [comment]
Ping @pan93412 

Promise.any 兼容貌似无了？
https://github.com/UnblockNeteaseMusic/server/commit/e88d9ff99320399ea8554cc3f38a1b128a6bef4f#diff-14c0a95a4651428b9aacda0f21c06f8eb3dda7ab68b9577f80a5d159796d6713L13419

**Comment by 1715173329** [comment]
idk，不过看起来和 @swc/core 有关系。。
