### ISSUE TITLE
内存溢出问题

### ISSUE THREAD

**Issue by Sricor** [UnblockNeteaseMusic/server#712]
在服务器上部署，通过pm2管理进程。在一段时间过后会出现内存占用异常情况
![5-25](https://user-images.githubusercontent.com/78024433/170254416-6775d744-8beb-4acb-b518-2edf78238f94.png)

已经尝试过
`NO_CACHE=true`

目前只能通过pm2重启来暂时解决
`pm2 start app.js --max-memory-restart=512M`

node version: v18.0.0

**Comment by Sricor** [comment]
![PM2](https://user-images.githubusercontent.com/78024433/170741047-e7aa6835-a95f-4ebc-a20f-812eeda2bd5f.png)

**Comment by pan93412** [comment]
可能要 profile 一下才知道是哪裡記憶體洩露了。

**Comment by gglilang** [comment]
我也是，部署在腾讯云，一直会有内存溢出问题，加上-s 严格模式就没有溢出问题了，可能是其他请求导致的
![image](https://user-images.githubusercontent.com/11524214/176994583-ede16d1d-ced6-440b-9371-0cddecb5b479.png)

**Comment by ArmsZhou** [comment]
是的，有内存溢出。我部署在我的软路由上，过段时间就断网了。😭

**Comment by chaos-zhu** [comment]
+1

**Comment by 1715173329** [comment]
> 加上-s 严格模式就没有溢出问题了，可能是其他请求导致的

#927 服务端被扫了，推荐开启严格模式

**Comment by lucas2021** [comment]
> > 加上-s 严格模式就没有溢出问题了，可能是其他请求导致的
> 
> #927 服务端被扫了，推荐开启严格模式

我也出现一样的问题，今天-s解决了
