### ISSUE TITLE
支持网易云新接口interface3.music.163.com/eapi/song/enhance/download/url/v1

### ISSUE THREAD

**Issue by nining377** [UnblockNeteaseMusic/server#743]
白名单中无此接口，导致安卓端较新版本无法命中代理，尝试在precompiled/app.js中添加白名单api/song/enhance/download/url/v1后走了代理，但是报以下错误：
`A error occurred in hook.request.after when hooking http://music.163.com/eapi/song/enhance/player/url
SyntaxError: Unexpected token { in JSON at position 25
    at JSON.parse (<anonymous>)
    at /data/data/com.netease.cloudmusic/files/script/precompiled/app.js:870:41
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Comment by 1715173329** [comment]
Please try #859
