### ISSUE TITLE
关于音源获取顺序的问题

### ISSUE THREAD

**Issue by Jerrymics** [UnblockNeteaseMusic/server#747]
问题：在网易云没有版权的情况下，服务器未按照设置的音源顺序进行歌曲的获取

测试设备：网易云音乐Android客户端、网易云音乐PC客户端

过程：

我使用Docker环境启动并设置了两个音源，`QQ 音乐`和`酷我音乐`

以下是我的Docker启动命令

```shell
docker run -p 8080:8080 -e ENABLE_LOCAL_VIP=true -e ENABLE_FLAC=true -e MIN_BR=320000 -e QQ_COOKIE="uin=XXX; qm_keyst=XXX" pan93412/unblock-netease-music-enhanced -o qq kuwo
```

我分别测试了两首网易云均无版权的音乐

- [*[Mojito](http://music.163.com/song?id=1454811222&userid=446819713)*](http://music.163.com/song?id=1454811222&userid=446819713) 此歌在`QQ音乐`需要购买专辑，但可以使用`酷我音乐`进行解析
- [*[笑纳](http://music.163.com/song?id=1488557040&userid=446819713)*](http://music.163.com/song?id=1488557040&userid=446819713) 此歌在`酷我音乐`无法正常将原唱进行解析，但可以使用`QQ音乐`进行解析

根据[[食用指南](https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-429515355)](https://github.com/nondanee/UnblockNeteaseMusic/issues/22#issuecomment-429515355) 进行设置，经过测试发现以上测试歌曲未能按照音源清单的优先级进行搜索，都是从`酷我音乐`进行解析的

![image](https://user-images.githubusercontent.com/46161570/174156801-1c15d2a6-0c76-455c-854a-fb80e46ea2df.png)

以上问题还请大佬看看 是不是我的食用姿势有问题

**Comment by Whuihuan** [comment]
我也是这个问题，用了migu就一直从migu解析，然后一直重复一首曲子

**Comment by jamxe** [comment]
请教QQ_cookie如何取得 已有绿钻但是没找到相关方法

**Comment by jamxe** [comment]
> > 请教QQ_cookie如何取得 已有绿钻但是没找到相关方法
> 
> javascript:(function()%7Bfunction getCookie(cookieName) %7Bvar strCookie %3D document.cookie%3Bvar arrCookie %3D strCookie.split("%3B ")%3Bfor (var i %3D 0%3B i < arrCookie.length%3B i%2B%2B) %7Bvar arr %3D arrCookie%5Bi%5D.split("%3D")%3Bif (cookieName %3D%3D arr%5B0%5D) %7Breturn arr%5B1%5D%7D%7Dreturn 0%7Dfunction put_qm_keyst(txt) %7Bif (txt %3D%3D 0) %7Balert("复制失败，请重新登录。")%3Breturn 0%7Dlet tmp_el %3D document.createElement("input")%3Btmp_el.setAttribute("readonly"%2C "readonly")%3Btmp_el.setAttribute("value"%2C txt)%3Bdocument.body.appendChild(tmp_el)%3Btmp_el.select()%3Btmp_el.setSelectionRange(0%2C 9999)%3Bif (document.execCommand("copy")) %7Bdocument.execCommand("copy")%7Ddocument.body.removeChild(tmp_el)%3Balert("复制成功")%7Dput_qm_keyst(getCookie("qm_keyst"))%7D)()
> 
> 加入收藏夹，在y.qq.com登录，然后点击就会复制，QQ_COOKIE就是 "uin=QQ号; qm_keyst=刚刚复制的的内容" 这段了

成功，非常感谢

**Comment by 1715173329** [comment]
Done in #866
