### ISSUE TITLE
允許自訂 pyncmd 音源的 Endpoint

### ISSUE THREAD

**Issue by ssrubsd** [UnblockNeteaseMusic/server#748]
使用pyncmd音源无法正常获取音乐，发现是此音源所用的反代服务器出问题了，提示：
{"message":"Requests rate limited. stage:trafficcontrol"}

测试链接：https://service-ghlrryee-1308098780.gz.apigw.tencentcs.com/release/pyncmd/track/GetTrackAudio?song_ids=26349641&bitrate=320000

**Comment by pan93412** [comment]
未來或許會考慮加上指定 PyNCMd 服務的設定。

**Comment by 1715173329** [comment]
https://github.com/mos9527/pyncmd/commit/32b5ae72e920982cecc3f1df87e53c2e93a16516
https://github.com/mos9527/pyncmd/commit/0e5dbe2b4e2ee1c38dc09ac70a7811bcdcb158d9

上游特意更改了配置，大概是不想被使用。
pyncmd 服务端并没有多少实例，不如允许自定义 cvip cookie？MITM 可以做文章。
