### ISSUE TITLE
Docker方式启动，后台歌曲匹配信息错误

### ISSUE THREAD

**Issue by joyoner** [UnblockNeteaseMusic/server#757]
启动方式：
docker run -d -m 300M --memory-swap -1 -e ENABLE_LOCAL_VIP=true -e NO_CACHE=true -e ENABLE_FLAC=true -e LOG_LEVEL=debug --network=host --restart=always --log-opt max-size=10m --name=music pan93412/unblock-netease-music-enhanced -e https://music.163.com -s -p 18080

测试环境：iOS ，证书已安装并信任

测试音乐：专辑中任意歌曲
https://music.163.com/#/album?id=208497

后台docker debug 日志如下，但实际匹配/播放器中播放的是 默认曲目60054701964.flac

BTW 如果日志贴的不够完整，可以实际使用上面的专辑复测下，谢谢。

`DEBUG: (request) Start requesting http://freetyst.nf.migu.cn/public/product9th/product43/product/24bit/2021/04/10/60054701964/60054701964.flac
DEBUG: (provider/match) The matched song is:
    size: 46711857
    br: 999000
    url: "http://freetyst.nf.migu.cn/public/product9th/product43/product/24bit/2021/04/10/60054701964/60054701964.flac"
    md5: null
DEBUG: (provider/match) The audio matched!
    source: "migu"
    info: {
      "name": "Старожилы любви",
      "id": 2069421,
      "alias": [],
      "duration": 252316,
      "album": {
        "name": "Скажи, что ты любишь",
        "id": 208497
      },
      "artists": [
        {
          "name": "Vitas",
          "id": 45634
        }
      ],
      "keyword": "Старожилы любви - Vitas"
    }
DEBUG: (provider/match) The data to replace:
    audioInfo: {
      "name": "Старожилы любви",
      "id": 2069421,
      "alias": [],
      "duration": 252316,
      "album": {
        "name": "Скажи, что ты любишь",
        "id": 208497
      },
      "artists": [
        {
          "name": "Vitas",
          "id": 45634
        }
      ],
      "keyword": "Старожилы любви - Vitas"
    }
    audioData: {
      "size": 46711857,
      "br": 999000,
      "url": "http://freetyst.nf.migu.cn/public/product9th/product43/product/24bit/2021/04/10/60054701964/60054701964.flac",
      "md5": null
    }
INFO: (provider/match) Replaced: [2069421] Старожилы любви
    audioId: 2069421
    songName: "Старожилы любви"
    url: "http://freetyst.nf.migu.cn/public/product9th/product43/product/24bit/2021/04/10/60054701964/60054701964.flac"`

**Comment by 1715173329** [comment]
#770
