### ISSUE TITLE
应版权方要求，此歌曲不支持下载

### ISSUE THREAD

**Issue by Creepercdn** [UnblockNeteaseMusic/server#769]
在更新新版网易云PC（Windows）端后，无法下载 可以正常播放的 VIP可下载音乐。
提示应版权方要求，此歌曲不支持下载
网易云音乐版本：2.10.2（build 200142) (patch 1:252aba9)
unblockneteasemusic版本： https://github.com/UnblockNeteaseMusic/server/commit/4585d0095587669100f0bd1d58a5ac14165b5c4a

**Comment by LiuXiaohuanhh** [comment]
> 在更新新版网易云PC（Windows）端后，无法下载 可以正常播放的 VIP可下载音乐。 提示应版权方要求，此歌曲不支持下载 网易云音乐版本：2.10.2（build 200142) (patch 1:252aba9) unblockneteasemusic版本： [4585d00](https://github.com/UnblockNeteaseMusic/server/commit/4585d0095587669100f0bd1d58a5ac14165b5c4a)

大哥，你的2.10.2可以正常解锁灰色音乐吗？

**Comment by Creepercdn** [comment]
> > 在更新新版网易云PC（Windows）端后，无法下载 可以正常播放的 VIP可下载音乐。 提示应版权方要求，此歌曲不支持下载 网易云音乐版本：2.10.2（build 200142) (patch 1:252aba9) unblockneteasemusic版本： [4585d00](https://github.com/UnblockNeteaseMusic/server/commit/4585d0095587669100f0bd1d58a5ac14165b5c4a)
> 
> 大哥，你的2.10.2可以正常解锁灰色音乐吗？

可以。

**Comment by hulinhao233** [comment]
> > > 在更新新版网易云PC（Windows）端后，无法下载 可以正常播放的 VIP可下载音乐。 提示应版权方要求，此歌曲不支持下载 网易云音乐版本：2.10.2（build 200142) (patch 1:252aba9) unblockneteasemusic版本： [4585d00](https://github.com/UnblockNeteaseMusic/server/commit/4585d0095587669100f0bd1d58a5ac14165b5c4a)
> > 
> > 
> > 大哥，你的2.10.2可以正常解锁灰色音乐吗？
> 
> 可以。

怎么弄的，我的不行，你用的什么版本，是npm的吗

**Comment by Creepercdn** [comment]
Git master

**Comment by 1715173329** [comment]
Please try #859

**Comment by Creepercdn** [comment]
仍然不行。replaced 的可以下载，没有被替换的无法下载。
