### ISSUE TITLE
高音质歌曲全部变成周杰伦唱的辣妹子是为啥

### ISSUE THREAD

**Issue by iseeyo** [UnblockNeteaseMusic/server#770]
高音质歌曲全部变成周杰伦唱的“冬虫夏草”是为啥，比如《红杏枝头春意闹》这首歌，播放出来的是周杰伦的“冬虫夏草”，而且无法切换回标清。
![0123E641](https://user-images.githubusercontent.com/7778828/177032243-1b07e1de-ffed-4292-b9b9-02898eb6e994.jpg)

**Comment by 1715173329** [comment]
可以从音源中去除 `migu`，听闻最近匹配有点问题。

**Comment by hugetiny** [comment]
哈哈哈啊哈哈哈哈哈哈啊哈

**Comment by catalpaaa** [comment]
XSWL
