### ISSUE TITLE
网易云客户端出现网络无法连接问题

### ISSUE THREAD

**Issue by yellowsae** [UnblockNeteaseMusic/server#776]
# 网易云客户端出现网络无法连接问题

我试了 Linux 和 windows 开启服务， 能够开启，经测试能够使用， 但是就是没有网络。 

![image](https://user-images.githubusercontent.com/58903178/177723342-0330c811-7d23-49c9-a139-f5c404c2ffd4.png)

![image](https://user-images.githubusercontent.com/58903178/177722807-5b2c8491-0968-46f9-88ea-01dce992857b.png)

**Comment by 1715173329** [comment]
请提供你的服务启动指令/参数。

**Comment by yellowsae** [comment]
```bash
git clone https://github.com/UnblockNeteaseMusic/server.git  && cd server
node app.js -o bilibili ytdlp

```

**Comment by yellowsae** [comment]
> ```shell
> git clone https://github.com/UnblockNeteaseMusic/server.git  && cd server
> node app.js -o bilibili ytdlp
> ```

尝试过很多版本， Linux 服务端一键安装，https://github.com/UnblockNeteaseMusic/install-scripts  和  unblockneteasemusic-win-x64.exe  都是这种情况

**Comment by yellowsae** [comment]
已解决问题： 我使用的网易云版本2.9.10 ，使用出现无法连接网络情况。 安装网易云2.9.5 后能够使用 。 

参考： https://github.com/nondanee/UnblockNeteaseMusic/issues/811

**Comment by exe65331729** [comment]
运行快捷方式属性中在目标尾部添加 --ignore-certificate-errors

**Comment by hulinhao233** [comment]
> 

不太行，我添加了之后运行快捷方式打开闪退，是winx64的可运行版本

**Comment by pan93412** [comment]
> 运行快捷方式属性中在目标尾部添加 --ignore-certificate-errors

我們的憑證應該是新的，不應該有憑證錯誤。更像是新版 NCM 採取更嚴格的驗證。

**Comment by hulinhao233** [comment]
> > 运行快捷方式属性中在目标尾部添加 --ignore-certificate-errors
> 
> 我們的憑證應該是新的，不應該有憑證錯誤。更像是新版 NCM 採取更嚴格的驗證。

我试了一下npm的方法，也不行
终端里有反应，网易云代理显示可用，但是网易云无连接，可能是还没有适配2.10.2？

**Comment by zch233** [comment]
自动升级了，怎么回退

**Comment by 1582421598** [comment]
新版本看起来加强了证书相关的验证，要么加[参数到网易云的快捷方式上](https://github.com/UnblockNeteaseMusic/server/issues/776#issuecomment-1178929697)，要么就把CA证书安装到根证书列表里。

**Comment by redn3ck** [comment]
2.9.10可用，刚才自动升级成2.10.2，复现楼主问题，代理可用，实际不能用

**Comment by redn3ck** [comment]
> 新版本看起来加强了证书相关的验证，要么加[参数到网易云的快捷方式上](https://github.com/UnblockNeteaseMusic/server/issues/776#issuecomment-1178929697)，要么就把CA证书安装到根证书列表里。

已测试安装根证书，可以解决网络问题，但无法解锁
![图片](https://user-images.githubusercontent.com/12512242/178220674-b9f36c78-55a6-4cee-abd8-d2011c24d0ce.png)

**Comment by qilinxinan** [comment]
之前也碰到这个问题，头大，后台去找绿色版，用的2.9.10.200061没有这个问题，绿色禁升级版本，目前非常稳定。

**Comment by firstuanl** [comment]
linux版没升级也不行了，

**Comment by acmida** [comment]
由大佬提供的历史版本安装包下载地址：https://blog.amarea.cn/archives/netease-cloudmusic-history-version.html

**Comment by Youmdzz2333** [comment]
换回2.9.10没有问题

**Comment by liuzhijie443** [comment]
> 

可用，谢谢。

**Comment by sakura-flutter** [comment]
> > 新版本看起来加强了证书相关的验证，要么加[参数到网易云的快捷方式上](https://github.com/UnblockNeteaseMusic/server/issues/776#issuecomment-1178929697)，要么就把CA证书安装到根证书列表里。
> 
> 已测试安装根证书，可以解决网络问题，但无法解锁 ![图片](https://user-images.githubusercontent.com/12512242/178220674-b9f36c78-55a6-4cee-abd8-d2011c24d0ce.png)

是的，只能2.9.10没有问题

**Comment by 1715173329** [comment]
Please try #859

**Comment by xinxinenjoy** [comment]
> 

快捷方式这个简单，但是怎么样能够一劳永逸的加到根目录呢？
