### ISSUE TITLE
注册成Windows Service后无法启动

### ISSUE THREAD

**Issue by WillemRumu** [UnblockNeteaseMusic/server#785]
v0.27.0-rc.6版下载的项目包，运行node nw.js后可以在任务管理器里看见unblockneteasecloudmusic.exe但是无法启动。网易云显示网络连接失败（网易云版本2.10.2），运行node app.js和可运行文件也不行了。是证书过期了吗？

**Comment by 1715173329** [comment]
#695 #780

**Comment by 1715173329** [comment]
Fixed.
