### ISSUE TITLE
调用接口方法在vercel出现错误

### ISSUE THREAD

**Issue by lqdahv** [UnblockNeteaseMusic/server#818]
在vercel上部署了接口，本地也部署了一个
我在本地上传入网易一首能播放的歌曲ID 1901371647
本地上能替换音源，但是vercel部署的不行。
![QQ截图20220809185956](https://user-images.githubusercontent.com/24808833/183632171-04c27efb-4a83-4590-a2ee-5b1e5b1b168b.png)
![QQ截图20220809190007](https://user-images.githubusercontent.com/24808833/183632203-323b8789-6805-4674-9499-a904a825838a.png)

发现vercel能替换音源的只有网易版权有问题才能替换，vip和网易正常歌曲都不能替换，本地部署的都能替换

这种情况有解决办法吗

**Comment by pan93412** [comment]
目前 UNM 還不支援 Vercel 喔，而且 log 太少也不清楚具體問題點。
