### ISSUE TITLE
MACOS客户端提示“无法添加播放”,客户端版本882

### ISSUE THREAD

**Issue by dycwuxing** [UnblockNeteaseMusic/server#823]
大佬,我是docker搭建的,ios手机可以正常使用
mac上使用pac代理,能够解灰,但是无法播放,请帮助看看还能如何改进?谢谢!

docker run  -d -p 6665:8080 -m 300M --memory-swap -1 -e ENABLE_LOCAL_VIP=true -e NO_CACHE=true -e ENABLE_FLAC=true -e NODE_ENV=production --restart=always --log-opt max-size=10m --name=yunmusic pan93412/unblock-netease-music-enhanced -e https://music.163.com/ -o kuwo ytdlp bilibili kugou -s -f 59.111.19.33

<img width="645" alt="image" src="https://user-images.githubusercontent.com/44988562/184133504-98549a28-4a80-4c08-9156-c42a71899526.png">
<img width="502" alt="image" src="https://user-images.githubusercontent.com/44988562/184133610-4645b7ea-39af-4a31-aabc-4883eb6383ab.png">

**Comment by dycwuxing** [comment]
补充一下:IOS不是设置代理pac,是用的loon添加的规则,另windows直接设置IE代理也是可行的,唯独mac客户端不成功

**Comment by morooi** [comment]
+1，也遇到了。只有 macOS 客户端不行，iOS 正常。
版本 2.3.9 (Build:880) (Patch:1:447d3f8)

启动参数 node app.js -o kugou kuwo migu -e https://music.163.com

**Comment by fangshaok** [comment]
我也不行了，大家可以先用 yesplaymusic 代替一下

**Comment by f0rdream** [comment]
FYI: 升级2.3.9 (Build:880) 遇到同样问题，降级到2.3.2 (832)后没问题了

**Comment by davidzhang12138** [comment]
2.3.8 版本没问题 降级吧

**Comment by showyoulove1990** [comment]
同样的问题，可有解决方案啊 各位大神？

**Comment by xsm1997** [comment]
windows 2.10.3 客户端遇到同样问题

**Comment by Mr-xn** [comment]
> 2.3.8 版本没问题 降级吧

MAC 版本下地址：[官方下载](https://d1.music.126.net/dmusic/NeteaseMusic_2.3.8_872_web.dmg) | [备份下载](https://we.tl/t-EClzDpGWHR)

**Comment by 1715173329** [comment]
please try #859

**Comment by 1715173329** [comment]
Fixed.
