### ISSUE TITLE
npx 运行不了？

### ISSUE THREAD

**Issue by CallMeChin** [UnblockNeteaseMusic/server#825]
<img width="719" alt="image" src="https://user-images.githubusercontent.com/77185235/184500223-28c8ff00-e5d1-41ed-bad3-a52db58377e5.png">

**Comment by pan93412** [comment]
成功復現：

<img width="777" alt="截圖 2022-08-29 下午3 44 19" src="https://user-images.githubusercontent.com/28441561/187150303-2dc9eaed-d3fb-447f-aa2c-e67fd19e0a1d.png">

**Comment by 1715173329** [comment]
问题在于缺少正确的 shebang，被默认使用 sh 执行了。
