### ISSUE TITLE
QQ/酷狗 播放不了了，酷狗搞了个网页版，只能播放一分钟，哎嗨害，蓝廋！

### ISSUE THREAD

**Issue by qq1147050160** [UnblockNeteaseMusic/server#843]
大神们，啥时候能更新一下QQ/酷狗呢？ 想用这两个源，下载上传云盘。其他源好多歌曲信息不匹配。网盘的纠正歌曲功能也关闭了

**Comment by SekiBetu** [comment]
国内音乐已经全正版化了，这个项目也是时候没用了

**Comment by qq1147050160** [comment]
哪怕需要提供Cookie也行，这样我就能开个临时vip下载到云盘里面，后面就能跨设备听了。

**Comment by 1715173329** [comment]
根据 #779 的回复 qq 音源应该还能正常使用，不过 cookie 有效期只有一天。
