### ISSUE TITLE
ERROR: (hook) A error occurred in hook.request.before when hooking https://interface3.music.163.com/eapi/ios/upgrade/get.

### ISSUE THREAD

**Issue by oqo0opo** [UnblockNeteaseMusic/server#847]
Server: commit 7b52caab3c6d4f40b5c1a1b1e7aed8244ecde85b
Client: IOS 8.8.21

node app.js -s -p 8083:8085 -o kuwo kugou qq migu bilibili -e http://music.163.com

ERROR: (hook) A error occurred in hook.request.before when hooking https://interface3.music.163.com/eapi/ios/upgrade/get.
    Error: aborted
        at connResetException (node:internal/errors:704:14)
        at abortIncoming (node:_http_server:625:17)
        at socketOnClose (node:_http_server:619:3)
        at TLSSocket.emit (node:events:525:35)
        at node:net:757:14
        at Socket.done (node:_tls_wrap:584:7)
        at Object.onceWrapper (node:events:628:26)
        at Socket.emit (node:events:513:28)
        at TCP.<anonymous> (node:net:757:14)
    code: ECONNRESET

**Comment by jackey-jiang** [comment]
I have the same question.请问有解决方案么,也是iOS,使用surge代理,目前同一份配置文件,Mac是完美运行,但iOS可以解锁现有歌单并听歌,但搜索查找和歌词啥的就没有了,不能搜索实在是太蛋疼,希望有大佬可以帮忙解答下,采用的自签证书方案
 控制台报错:
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/10288803/191649585-8fe3de87-c636-47c8-ad71-0f434470476b.png">
iOS可解锁并听歌:
![IMG_7870](https://user-images.githubusercontent.com/10288803/191650094-b7aab2cd-01e9-43bb-bec1-9450ba8b6acc.PNG)
无法搜索:
![IMG_7871](https://user-images.githubusercontent.com/10288803/191650118-389ae886-07ac-4d49-90a6-aad6bfd027b1.PNG)
无法查看评论:
![IMG_7872](https://user-images.githubusercontent.com/10288803/191650149-a4b30def-bbf8-4d8a-8a38-f081b3e9a7d4.PNG)
综上所述:怀疑是这个(https://interface3.music.163.com/eapi/ios/upgrade/get)接口无法正常返回导致

**Comment by 1715173329** [comment]
network issue
