### ISSUE TITLE
UWP版的网易云显示一堆TUNNEL - music.163.com:443

### ISSUE THREAD

**Issue by LQTseng** [UnblockNeteaseMusic/server#848]
在本地跑项目之后打开UWP版的网易云显示一堆TUNNEL - music.163.com:443怎么回事？网易云也提示网络异常
![image](https://user-images.githubusercontent.com/109683666/188126008-715c2adc-4f2a-4828-a383-8a96a474ed60.png)
![image](https://user-images.githubusercontent.com/109683666/188126151-b962d62a-7910-4205-a540-29fc7ce72967.png)

**Comment by 1715173329** [comment]
请监听 https 端口，设置 endpoint

**Comment by LQTseng** [comment]
> 



> 请监听 https 端口，设置 endpoint

设置 endpoint具体应该怎么操作呢
