### ISSUE TITLE
win-exe指定端口后无法连接

### ISSUE THREAD

**Issue by Elizabeth-1992** [UnblockNeteaseMusic/server#850]
win11系统，使用win-exe运行时使用-p指定端口启动后，网易云音乐测试代理显示该代理可用，但播放时显示无法连接网络。

**Comment by 1715173329** [comment]
请确认您已经指定 https 端口，请确认您的版本低于或等于 2.9.10

**Comment by Elizabeth-1992** [comment]
使用版本2.9.9，怎么确定指定的是否是https端口？

**Comment by thanksshu** [comment]
启动参数 `-p 8080:8081`

**Comment by Elizabeth-1992** [comment]
非常感谢，好用了。

**Comment by thanksshu** [comment]
不用客气。如果问题已经解决，请关闭 issue。
