### ISSUE TITLE
部分歌曲点击后提示无法添加播放

### ISSUE THREAD

**Issue by MustardWithRice** [UnblockNeteaseMusic/server#882]
如题，比如点击赵雷的新歌，会提示无法添加播放

**Comment by 1715173329** [comment]
什么歌，什么平台，什么环境

**Comment by MustardWithRice** [comment]
> 什么歌，什么平台，什么环境

macos, 歌曲名称：我记得（赵雷）

**Comment by 4860575** [comment]
server:ubuntu-22.04

**Comment by 1715173329** [comment]
应该是部分 hook 没有完全替代造成的。最近几天看看。

**Comment by yujincheng08** [comment]
![image](https://user-images.githubusercontent.com/5022927/196891902-c712cf2c-e1cd-4812-9bd0-1e5bcb67ebcc.png)

https://music.163.com/song?id=516653091&userid=84211842

Same issue here.
