### ISSUE TITLE
SOURCE环境变量没有在任何地方被使用

### ISSUE THREAD

**Issue by umonaca** [UnblockNeteaseMusic/server#902]
`docker-compose.yml`中有`SOURCE`这一环境变量，但是这一变量并没有用在程序的任何地方。也就是说如果我没有看错的话，这里的设置是无效的。
https://github.com/UnblockNeteaseMusic/server/blob/091314e0022be8f05f7a2c853ab23dd8a11dc38d/docker-compose.yml#L8
在调试Docker的时候发现了这个问题，设置`SOURCE`没有达到预期效果，而README文档中也没有提，于是搜索了一下代码发现有这个问题。

**Comment by 1715173329** [comment]
this file is poorly maintained and needs more love

**Comment by umonaca** [comment]
> this file is poorly maintained and needs more love

Hahahaha.  
Do you want to modify this file only, or change the code of the main program to accept environment variable `SOURCE` as well?
