### ISSUE TITLE
【已解决，附后台运行脚本】无法启动，Error: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by Jenking-Zhang** [UnblockNeteaseMusic/server#91]
`Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 80
}`
请问一下这个是什么原因呢？谢谢！！
感觉像是网络原因，连不上某个服务一样~~我之前试过连手机热点启动成功过，但是现在就怎么都启动不了了~

**Comment by pan93412** [comment]
試試看重開電腦？我猜是有服務佔住 80 port。

**Comment by Jenking-Zhang** [comment]
> 試試看重開電腦？我猜是有服務佔住 80 port。
重启过了~目前使用的是-u指定上游 http / https 代理跑起来的~但是还是想解决下，怎么不适用代理跑，这样就可以用unblockneteasemusic-desktop

**Comment by 1715173329** [comment]
https://github.com/1715173329/UnblockNeteaseMusic#%E6%96%B9%E6%B3%95-1-%E4%BF%AE%E6%94%B9-hosts
你是修改过 hosts 吗？

**Comment by Jenking-Zhang** [comment]
> https://github.com/1715173329/UnblockNeteaseMusic#%E6%96%B9%E6%B3%95-1-%E4%BF%AE%E6%94%B9-hosts 你是修改过 hosts 吗？

hosts是空的~也没有看到有程序占用80端口，感觉像是我家里的网络环境不能裸连某些服务导致的~github就不能裸连

**Comment by jayfongs** [comment]
![image](https://user-images.githubusercontent.com/17779577/126459929-e6655763-ef1d-4a83-be86-6cf550a48f2c.png)

这个和我的有点像，但是我这个是用了公司的DNS才导致的，好像是因为之前公司改过DNS的啥东西才出现的这种情况

**Comment by Jenking-Zhang** [comment]
> ![image](https://user-images.githubusercontent.com/17779577/126459929-e6655763-ef1d-4a83-be86-6cf550a48f2c.png)
> 
> 这个和我的有点像，但是我这个是用了公司的DNS才导致的，好像是因为之前公司改过DNS的啥东西才出现的这种情况

你解决了么~~不知道是哪个服务没办法裸连

**Comment by jayfongs** [comment]
> > ![image](https://user-images.githubusercontent.com/17779577/126459929-e6655763-ef1d-4a83-be86-6cf550a48f2c.png)
> > 这个和我的有点像，但是我这个是用了公司的DNS才导致的，好像是因为之前公司改过DNS的啥东西才出现的这种情况
> 
> 你解决了么~~不知道是哪个服务没办法裸连

没有，我没有权限改公司DNS配置。我是在我的电脑上删了公司的DNS就可以了，我没有在本地运行使用。我是部署在服务器上使用的

**Comment by luoxingran** [comment]
我也出现这个问题，你可以试试更换下node版本，我用32位后没有出现这个问题。

**Comment by whosydd** [comment]
host换成0.0.0.0试试
```bash
node app.js -a 0.0.0.0
```

**Comment by Cl0ud9** [comment]
请问楼主解决了这个问题吗，我刚开始用的时候正常运行，用了两天后打开就提示和你一样的错误了，不知道哪里出了问题。

**Comment by pan93412** [comment]
你們試試看把 port 改成 80 以外的值？我覺得是有軟體佔用 :80。

**Comment by 1715173329** [comment]
看起来像是程序在向 127.0.0.1 发起请求？有检查过 DNS 吗？

**Comment by Cl0ud9** [comment]
> ~你們試試看把 port 改成 80 以外的值？我覺得是有軟體佔用 :80。~ 不太對，不應該這樣。
> 
> 你們可以幫我停用 HTTPDNS 看看嗎？如果可以的話希望能夠讓我遠端測試，方便我解決。

你好，我尝试停用HTTPDNS，但是不知道环境变量具体如何设置。

**Comment by 1715173329** [comment]
> 你好，我尝试停用HTTPDNS，但是不知道环境变量具体如何设置。

`env DISABLE_HTTPDNS=true node <args>`

**Comment by Cl0ud9** [comment]
> > 你好，我尝试停用HTTPDNS，但是不知道环境变量具体如何设置。
> 
> `env DISABLE_HTTPDNS=true node app.js <args>`

我是windows系统，DISABLE_HTTPDNS是无效指令，该如何设置呢？

**Comment by pan93412** [comment]
> > > 你好，我尝试停用HTTPDNS，但是不知道环境变量具体如何设置。
> > 
> > 
> > `env DISABLE_HTTPDNS=true node app.js <args>`
> 
> 我是windows系统，DISABLE_HTTPDNS是无效指令，该如何设置呢？

```batch
set DISABLE_HTTPDNS=true
node app.js ...
```

**Comment by Cl0ud9** [comment]
> > > > 你好，我尝试停用HTTPDNS，但是不知道环境变量具体如何设置。
> > > 
> > > 
> > > `env DISABLE_HTTPDNS=true node app.js <args>`
> > 
> > 
> > 我是windows系统，DISABLE_HTTPDNS是无效指令，该如何设置呢？
> 
> ```batchfile
> set DISABLE_HTTPDNS=true
> node app.js ...
> ```

你好，尝试禁用后还是出现相同的错误，并且我换了一台电脑测试还是一样。
![1](https://user-images.githubusercontent.com/30020035/132978282-19083134-7fe6-4c6f-9df4-97ed45d23dd7.png)

**Comment by Jenking-Zhang** [comment]
> 请问楼主解决了这个问题吗，我刚开始用的时候正常运行，用了两天后打开就提示和你一样的错误了，不知道哪里出了问题。

可以100%确定是网络环境的问题，-u指定代理可以运行，笔记本拿到单位也可以用，在家连手机流量开的热点也可以用~~就不知道是我家的网络DNS没有解析到域名的问题，还是我家的网络环境就没办法连接到服务的问题了，如果是DNS解析问题，如果能知道网络中是哪个域名解析有问题，换DNS或者hosts就可以比较好的解决，但是我目前就指定代理用的，用点代理流量嘛~

**Comment by Jenking-Zhang** [comment]
用最新的exe版本可以完美运行，感谢大佬们的贡献。分享一下我的运行后台脚本
`Dim UnblockNeteaseMusic
Set fso = CreateObject("Scripting.FileSystemObject")
Set WshShell = WScript.CreateObject("WScript.Shell")
'程序文件名
exeName= "unblockneteasemusic-win-x64.exe"
'程序监听端口
listenPort = "16163:16164"
'获取当前路径
currentPath = fso.GetFile(Wscript.ScriptFullName).ParentFolder.Path & "\"
'程序路径
exePath = currentPath & exeName
'检查进程是否存在
strComputer = "."
Set objWMIService = GetObject("winmgmts:{impersonationLevel=impersonate}!\\" & strComputer & "\root\cimv2")
Set colProcessList = objWMIService.ExecQuery("Select * from Win32_Process Where Name = " & "'" & exeName & "'")
If colProcessList.Count > 0 Then
    '程序运行中，结束程序
    WshShell.Run "cmd.exe /C Taskkill /t /f /im " & exeName,0, False
    '等待3秒
    WScript.Sleep 3000
End If
'获取当前时间并格式化
nowTime = right("00"&month(now),2) & "-" & right("00"&day(now),2) & "_" & right("00"&hour(now),2) & "-"  & right("00"&minute(now),2) & "-"  & right("00"&Second(now),2)
'日志目录
logFilePath = currentPath & "unblockneteasemusic.log" & "\"
'目录检查，不存在就创建
If fso.folderExists( logFilePath ) = False Then
        'Msgbox "目录不存在！"
        fso.CreateFolder(logFilePath)
End If
'日志文件完整路径
logFile = logFilePath & "app." & nowTime & ".log"
'设置运行命令及参数
cmdLine = "cmd /c " & exePath & " -p " & listenPort & " > " & logFile & " 2>&1"
'启动软件
WshShell.Run cmdLine, 0, False
'Msgbox "启动成功!"
'等待1秒
'WScript.Sleep 1000
'打印运行命令
'Wscript.echo cmdLine
Set WshShell = Nothing
Set fso = Nothing
'退出脚本
WScript.quit`
