### ISSUE TITLE
网易云是不是又修改解析的ip地址了？

### ISSUE THREAD

**Issue by pianississimo** [UnblockNeteaseMusic/server#912]
最新遇到的报错：

Error: connect ECONNREFUSED 59.111.239.62:80

请问是已知问题嘛？

**Comment by 1715173329** [comment]
I don't see this issue, check your network

**Comment by ssrubsd** [comment]
经测试，pyncmd确实还是不能在无代理的环境下使用
同一首歌在已设置FOLLOW_SOURCE_ORDER且pyncmd为音源顺序第一的情况下不开启代理会用kuwo音源，而开启代理后则是pyncmd
![image](https://user-images.githubusercontent.com/59917319/202073082-0f6b083f-8f60-4d4b-86d3-430db5361e63.png)
![image](https://user-images.githubusercontent.com/59917319/202073139-69cea956-7391-41f1-94dd-5d203a375f37.png)
