### ISSUE TITLE
播放正常，但下载在非网易云会员情况下会被拒绝下载

### ISSUE THREAD

**Issue by smmya** [UnblockNeteaseMusic/server#921]
因版权方要求，该歌曲暂不支持下载，国内服务器，已经正确配置程序了
![image](https://user-images.githubusercontent.com/69052436/201692493-64e0d374-2404-4ab3-af46-8b2fdbb81533.png)

**Comment by 1715173329** [comment]
版本号？

**Comment by smmya** [comment]
> 版本号？
抱歉，一下子没看到回复，
pc网易云版本为，2.10.12 ， 2.10.5都无法下载
服务端为该issue发布时直接下载项目源码，win-server运行，本地的openwrt版本luci-app也是一样的的情况

**Comment by smmya** [comment]
然后使用网易云会员时下载的文件也只能是网易云自有音源

上文说的不能下载是指绝大部分音乐，包括解黑以后的音乐

**Comment by 1715173329** [comment]
信任证书了吗，我在 2.10.5 测试没发现问题。

**Comment by smmya** [comment]
> 信任证书了吗，我在 2.10.5 测试没发现问题。

不信任证书直接就是无网络的

**Comment by 1715173329** [comment]
无法复现你的情况。网易云音乐官方最新版本也就 2.10.6，不知道你的 2.10.12 哪儿来的。

**Comment by 1715173329** [comment]
如果你使用的是 release，则需要使用当前最新提交版本。

**Comment by smmya** [comment]
> 如果你使用的是 release，则需要升级到当前最新提交版本。

不能使用release版本？

**Comment by 1715173329** [comment]
https://github.com/UnblockNeteaseMusic/server/actions/runs/3861195521
用这里的版本试一下

**Comment by FlysoftBeta** [comment]
我也有同样的问题，网易云版本2.10.6，希望修复一下

**Comment by Creepercdn** [comment]
我刚写了一个简单的 BetterNCM 插件，可以解决这个问题。

<https://gist.github.com/Creepercdn/ab10fe71c690a87bcd4a90f8caf2d568>

**Comment by windy1021** [comment]
> 我刚写了一个简单的 BetterNCM 插件，可以解决这个问题。
> 
> https://gist.github.com/Creepercdn/ab10fe71c690a87bcd4a90f8caf2d568

大佬，链接打不开呀

**Comment by windy1021** [comment]
> 我刚写了一个简单的 BetterNCM 插件，可以解决这个问题。
> 
> https://gist.github.com/Creepercdn/ab10fe71c690a87bcd4a90f8caf2d568

大佬请问要怎么使用？怎么打包成插件？

**Comment by Creepercdn** [comment]
> > 我刚写了一个简单的 BetterNCM 插件，可以解决这个问题。
> > https://gist.github.com/Creepercdn/ab10fe71c690a87bcd4a90f8caf2d568
> 
> 大佬请问要怎么使用？怎么打包成插件？

在 C:\betterncm\plugins_dev\ 下创建一个文件夹，然后把这两个文件下载到这个文件夹里就可以了。

**Comment by windy1021** [comment]
> > > 我刚写了一个简单的 BetterNCM 插件，可以解决这个问题。
> > > https://gist.github.com/Creepercdn/ab10fe71c690a87bcd4a90f8caf2d568
> > 
> > 
> > 大佬请问要怎么使用？怎么打包成插件？
> 
> 在 C:\betterncm\plugins_dev\ 下创建一个文件夹，然后把这两个文件下载到这个文件夹里就可以了。

谢谢大佬，但我试了一下还是显示无版权不支持下载

**Comment by Creepercdn** [comment]
> > > > 我刚写了一个简单的 BetterNCM 插件，可以解决这个问题。
> > > > https://gist.github.com/Creepercdn/ab10fe71c690a87bcd4a90f8caf2d568
> > > 
> > > 
> > > 大佬请问要怎么使用？怎么打包成插件？
> > 
> > 
> > 在 C:\betterncm\plugins_dev\ 下创建一个文件夹，然后把这两个文件下载到这个文件夹里就可以了。
> 
> 谢谢大佬，但我试了一下还是显示无版权不支持下载

已更改，请升级到 NCM 最新版本后重新安装这个插件。然后确保 NCM 版本的 Patch 部分为 6f4f404。

**Comment by windy1021** [comment]
> > > > > 我刚写了一个简单的 BetterNCM 插件，可以解决这个问题。
> > > > > https://gist.github.com/Creepercdn/ab10fe71c690a87bcd4a90f8caf2d568
> > > > 
> > > > 
> > > > 大佬请问要怎么使用？怎么打包成插件？
> > > 
> > > 
> > > 在 C:\betterncm\plugins_dev\ 下创建一个文件夹，然后把这两个文件下载到这个文件夹里就可以了。
> > 
> > 
> > 谢谢大佬，但我试了一下还是显示无版权不支持下载
> 
> 已更改，请升级到 NCM 最新版本后重新安装这个插件。然后确保 NCM 版本的 Patch 部分为 6f4f404。

请问下ncm的patch要在哪里查看🤣我只找到了网易云版本的patch

**Comment by Creepercdn** [comment]
> > 已更改，请升级到 NCM 最新版本后重新安装这个插件。然后确保 NCM 版本的 Patch 部分为 6f4f404。
> 
> 请问下ncm的patch要在哪里查看🤣我只找到了网易云版本的patch

NCM 就是网易云音乐。

**Comment by windy1021** [comment]
> > > 已更改，请升级到 NCM 最新版本后重新安装这个插件。然后确保 NCM 版本的 Patch 部分为 6f4f404。
> > 
> > 
> > 请问下ncm的patch要在哪里查看🤣我只找到了网易云版本的patch
> 
> NCM 就是网易云音乐。
请问下哪个版本的网易云的patch是6f4f404？我试了2.10.6和2.10.8都不是

**Comment by Creepercdn** [comment]
> > > 请问下ncm的patch要在哪里查看🤣我只找到了网易云版本的patch
> > 
> > 
> > NCM 就是网易云音乐。
> 请问下哪个版本的网易云的patch是6f4f404？我试了2.10.6和2.10.8都不是


可以直接把 [这一行](https://gist.github.com/Creepercdn/ab10fe71c690a87bcd4a90f8caf2d568#file-manifest-json-L17) 中的 6f4f404 替换成你的 patch。

**Comment by windy1021** [comment]
> > > > 请问下ncm的patch要在哪里查看🤣我只找到了网易云版本的patch
> > > 
> > > 
> > > NCM 就是网易云音乐。
> > > 请问下哪个版本的网易云的patch是6f4f404？我试了2.10.6和2.10.8都不是
> 
> 可以直接把 [这一行](https://gist.github.com/Creepercdn/ab10fe71c690a87bcd4a90f8caf2d568#file-manifest-json-L17) 中的 6f4f404 替换成你的 patch。

感谢！！解决了！！大佬牛批！

**Comment by chen310** [comment]
> > > > 请问下ncm的patch要在哪里查看🤣我只找到了网易云版本的patch
> > > 
> > > 
> > > NCM 就是网易云音乐。
> > > 请问下哪个版本的网易云的patch是6f4f404？我试了2.10.6和2.10.8都不是
> 
> 可以直接把 [这一行](https://gist.github.com/Creepercdn/ab10fe71c690a87bcd4a90f8caf2d568#file-manifest-json-L17) 中的 6f4f404 替换成你的 patch。

https://gist.github.com/Creepercdn/ab10fe71c690a87bcd4a90f8caf2d568#file-manifest-json-L17
可以直接写成 `orpheus://orpheus/pub/core` 后面那一串不用写

**Comment by windy1021** [comment]
> > > > 请问下ncm的patch要在哪里查看🤣我只找到了网易云版本的patch
> > > 
> > > 
> > > NCM 就是网易云音乐。
> > > 请问下哪个版本的网易云的patch是6f4f404？我试了2.10.6和2.10.8都不是
> 
> 可以直接把 [这一行](https://gist.github.com/Creepercdn/ab10fe71c690a87bcd4a90f8caf2d568#file-manifest-json-L17) 中的 6f4f404 替换成你的 patch。

大佬请问网易云更新后还能用吗？我看代码上面是2.10.6-2.10.8？

**Comment by rsp4jack** [comment]
最新的 UnblockNeteaseMusic 应该不需要这个插件了。
