### ISSUE TITLE
0.27.0版本 内存溢出严重

### ISSUE THREAD

**Issue by chaos-zhu** [UnblockNeteaseMusic/server#927]
启动一分钟
![image](https://user-images.githubusercontent.com/44160914/202340655-2d09b3fb-7f47-4f20-967b-e7af153a8adc.png)

启动三分钟
![image](https://user-images.githubusercontent.com/44160914/202340713-801434cd-a151-4ec8-8068-71f564f2d2dd.png)

启动五分钟
![image](https://user-images.githubusercontent.com/44160914/202340809-c1924daf-4e18-45f5-b2b3-087da2adc067.png)

**Comment by chaos-zhu** [comment]
centos8 
node.js v16.17.0

**Comment by Hutianming** [comment]
同样问题，运行后CPU直接拉满，负载也满了，有解决方法吗

**Comment by chaos-zhu** [comment]
> 同样问题，运行后CPU直接拉满，负载也满了，有解决方法吗

还一直跑流量，1h2g5m的vps带宽直接占满

**Comment by chaos-zhu** [comment]
> 同样问题，运行后CPU直接拉满，负载也满了，有解决方法吗

pm2定时重启也没啥用，负载很高，带宽还是一直占用. 看看作者有啥子解决办法吧

**Comment by chaos-zhu** [comment]
> 同样问题，运行后CPU直接拉满，负载也满了，有解决方法吗

排查了下。MD，被人当肉鸡了，几个俄罗斯的IP一直在刷。

解决：开严格模式，用pac代理解决

**Comment by Hutianming** [comment]
> > 同样问题，运行后CPU直接拉满，负载也满了，有解决方法吗
> 
> 排查了下。MD，被人当肉鸡了，几个俄罗斯的IP一直在刷。
> 
> 解决：开严格模式，用pac代理解决

开启严格模式后，服务器能接受到请求，但是网易云音乐这边一直处于加载情况，PAC是怎么配置的

**Comment by chaos-zhu** [comment]
> > > 同样问题，运行后CPU直接拉满，负载也满了，有解决方法吗
> > 
> > 
> > 排查了下。MD，被人当肉鸡了，几个俄罗斯的IP一直在刷。
> > 解决：开严格模式，用pac代理解决
> 
> 开启严格模式后，服务器能接受到请求，但是网易云音乐这边一直处于加载情况，PAC是怎么配置的

改端口，配host也行。readme里有
