### ISSUE TITLE
bilibili源无法使用

### ISSUE THREAD

**Issue by wukibaka** [UnblockNeteaseMusic/server#928]
如图
直接访问显示 403 forbidden
客户端显示无法缓冲歌曲
![Screenshot_20221119-012210.png](https://user-images.githubusercontent.com/51240031/202764784-4c829242-eb92-4ecf-8f17-e495243fa2cb.png)
![Screenshot_20221119-012249.png](https://user-images.githubusercontent.com/51240031/202764645-c4707946-c66c-4db0-aaec-56d7dfe0bbd8.png)![Screenshot_20221119-012317.png](https://user-images.githubusercontent.com/51240031/202764734-2103f45b-67c7-42b0-a5e4-afa7ad6bde0f.png)

**Comment by 1715173329** [comment]
要特定的 header 才能访问，正确信任证书了吗？

**Comment by wukibaka** [comment]
> 要特定的 header 才能访问，正确信任证书了吗？

用的是杜比大喇叭那个模块

**Comment by 1715173329** [comment]
emmm 模块的话可能用不了，请尝试使用其他源。

**Comment by wukibaka** [comment]
现在的问题是 安卓怎么安装crt证书 安卓的系统证书都是.0后缀的
![Screenshot_20221119-014255.png](https://user-images.githubusercontent.com/51240031/202768372-c7079adf-1591-4f05-a614-37e7a829328e.png)

**Comment by 1715173329** [comment]
这个 filename 是 openssl 生成的摘要，简单点可以先信任为用户证书，然后再从 `/data/misc/user/0/cacerts-added` 复制，记得处理权限

**Comment by wukibaka** [comment]
> 这个 filename 是 openssl 生成的摘要，简单点可以先信任为用户证书，然后再从 `/data/misc/user/0/cacerts-added` 复制，记得处理权限

行 我试试

**Comment by wukibaka** [comment]
安装证书后依旧无法播放 只能交给模块作者来修了
![Screenshot_20221119-020441.png](https://user-images.githubusercontent.com/51240031/202773000-9d1b331f-efc3-4bd6-93bd-180a554f2cdb.png)

**Comment by 1715173329** [comment]
试试手动指定代理，记得设置 endpoint

**Comment by wukibaka** [comment]
> 试试手动指定代理，记得设置 endpoint

怎么设置呢 在这方面我是小白🥲

**Comment by wukibaka** [comment]
用“茉莉”的http代理 代理网易云音乐也会出现无法缓存bilibili源歌曲的情况
![Screenshot_20221119-231039~2.png](https://user-images.githubusercontent.com/51240031/202857650-72558db9-bb59-4bf8-b42d-2727598b7e15.png)![Screenshot_20221119-231035.png](https://user-images.githubusercontent.com/51240031/202857668-a1242cea-318d-4354-bffd-fe2529e26396.png)

**Comment by wukibaka** [comment]
配置apn倒是可以 （没装证书）
![Screenshot_20221119-231617~2.png](https://user-images.githubusercontent.com/51240031/202857867-0935b072-7eaa-4b16-a93c-e85c232936d5.png)![Screenshot_20221119-231703.png](https://user-images.githubusercontent.com/51240031/202857869-4e46459c-9764-4079-8e1c-d715f9a469cf.png)

**Comment by wukibaka** [comment]
> 用“茉莉”的http代理 代理网易云音乐也会出现无法缓存bilibili源歌曲的情况
> ![Screenshot_20221119-231039~2.png](https://user-images.githubusercontent.com/51240031/202857650-72558db9-bb59-4bf8-b42d-2727598b7e15.png)![Screenshot_20221119-231035.png](https://user-images.githubusercontent.com/51240031/202857668-a1242cea-318d-4354-bffd-fe2529e26396.png)

设置endpoint后 这种方法能听bilibili源了

**Comment by 1715173329** [comment]
可能是大喇叭没有设置 endpoint，所以 bilibili 的请求 hook 不到了。
bilibili 的资源要求特殊的 header，直接访问会 403。
这属于大喇叭的问题，关闭 issue。

**Comment by wukibaka** [comment]
> 可能是大喇叭没有设置 endpoint，所以 bilibili 的请求 hook 不到了。
> bilibili 的资源要求特殊的 header，直接访问会 403。
> 这属于大喇叭的问题，关闭 issue。

行吧 大喇叭停更了这个bug多半不会修了 不过找到了更好的方法
https://rushb.pro/article/Magisk-ub.html
