### ISSUE TITLE
MacOS 13 无法播放

### ISSUE THREAD

**Issue by fangshaok** [UnblockNeteaseMusic/server#937]
**之前更新 macOS13 之后，配合使用的 clash x Pro 因为进程匹配问题失效我就没有管了，前两天更新顺便弄了一下，进程匹配之后也没法使用，我还怀疑是clash 的问题，换 surge 流量都代理了发现也没有变化**
![image](https://user-images.githubusercontent.com/22343664/203698051-f9a1d483-20e5-47ad-9f62-9bbb4fe216b5.png)
**surge 增强模式也关闭试过，没有影响
然后重新安装项目自签证书，一点用没有，歌曲都是灰色的**
![image](https://user-images.githubusercontent.com/22343664/203698191-2a4ea3fb-0230-4a48-a5c9-686344dae8fa.png)
**这是输出 log**
![image](https://user-images.githubusercontent.com/22343664/203698443-709aa96e-392b-49e0-80fd-7ac653ab6f47.png)

**Comment by 1715173329** [comment]
可能存在的问题是网易云 api 强制使用 sdch 压缩了

**Comment by 1715173329** [comment]
SSL 的问题已在 #1035 修复
