### ISSUE TITLE
歌单广场页面加载不出来

### ISSUE THREAD

**Issue by easyhard007** [UnblockNeteaseMusic/server#941]
ios端网易云音乐，配合shadowrocket的http代理使用，并打开全局代理，服务器未开启-s严格模式。但是无法打开歌单广场页面，其他一切正常。启动参数：./unblockneteasemusic-linux-x64 -o kuwo -p 12033 -f 59.111.19.33 -e "https://music.163.com"

**Comment by 1715173329** [comment]
需要开启 https 端口，参见 README

**Comment by easyhard007** [comment]
开启https 端口后问题解决，启动参数： ./unblockneteasemusic-linux-x64 -o kuwo -p 12033:12034 -f 59.111.19.33 -e "https://music.163.com/"
