### ISSUE TITLE
QQ音乐 开启高音质后404

### ISSUE THREAD

**Issue by lvdongyi** [UnblockNeteaseMusic/server#942]
下图是ENABLE_FLAC=FALSE时，可以正常使用
![image](https://user-images.githubusercontent.com/24621834/204736753-a602c265-143c-480a-b859-937d6f6c732d.png)
ENABLE_FLAC=TRUE时会404，第一行是输出了一下cookie，cookie应该是正确的
![image](https://user-images.githubusercontent.com/24621834/204737220-f2365e12-1d94-4d7b-b5b4-34f9cd80faed.png)

**Comment by 1715173329** [comment]
qq 音乐是真的不干人事，现在走网页 api 只有 128k （可能都不到）的音质。。

**Comment by xsm1997** [comment]
@1715173329  大佬，这样的话，会员也获取不到flac了啊。我这里使用会员账号的cookie进行解析，用之前的代码是可以获取到flac的，改动之后会员也获取不到了。建议回滚commit。

还有这个404的问题我也发现了，但是仅针对于部分歌曲，不是全部歌曲，具体不知道咋回事。添加其他源之后可以用其他源获取到。

@lvdongyi 建议非会员用户添加多个源，或者禁用掉flac。我是使用无头浏览器解决qq音乐的cookie只有24小时有效期的问题的。

**Comment by 1715173329** [comment]
> @1715173329 大佬，这样的话，会员也获取不到flac了啊。我这里使用会员账号的cookie进行解析，用之前的代码是可以获取到flac的，改动之后会员也获取不到了。建议回滚commit。
> 
> 还有这个404的问题我也发现了，但是仅针对于部分歌曲，不是全部歌曲，具体不知道咋回事。添加其他源之后可以用其他源获取到。
> 
> @lvdongyi 建议非会员用户添加多个源，或者禁用掉flac。我是使用无头浏览器解决qq音乐的cookie只有24小时有效期的问题的。

我为了测这个特意去开的个会员，寄的。周杰伦这类直接 404，M500 都不给。还有些给 M800，FLAC 是没有的。

**Comment by xsm1997** [comment]
周杰伦确实没有，但相当一部分是有flac的，比如大部分acg歌曲。

**Comment by 1715173329** [comment]
实话说我刚刚去试了下，没找到有什么 acg 能获取 flac，any sample？
qq 音乐这么搞，不如酷我 + 咪咕了其实。

**Comment by xsm1997** [comment]
https://music.163.com/song?id=1813278385
https://music.163.com/song?id=1895615804
https://music.163.com/song?id=1422198842
https://music.163.com/song?id=438981798
https://music.163.com/song?id=1491205309
https://music.163.com/song?id=1472255147
使用改动之前的版本配合会员可以自动解锁到flac

**Comment by 1715173329** [comment]
emmm... 那大概是我们听歌类型不同了，我搜的几首都是寄。
可以把 match 的那个状态码检测搬过来，这样就可以实现 fallback。
我不会 js，写得也许比较丑，能帮忙优化下的话就帮大忙了。

```patch
--- a/src/provider/qq.js
+++ b/src/provider/qq.js
@@ -57,7 +57,7 @@ const single = (id, format) => {
 					param: {
 						guid: (Math.random() * 10000000).toFixed(0),
 						loginflag: 1,
-						filename: [format.join(id.file)],
+						filename: format[0] ? [format.join(id.file)] : null,
 						songmid: [id.song],
 						songtype: [0],
 						uin,
@@ -71,9 +71,18 @@ const single = (id, format) => {
 		.then((response) => response.json())
 		.then((jsonBody) => {
 			const { sip, midurlinfo } = jsonBody.req_0.data;
-			return midurlinfo[0].purl
-				? sip[0] + midurlinfo[0].purl
-				: Promise.reject();
+			if (!midurlinfo[0].purl) return Promise.reject();
+
+			const playurl = sip[0] + midurlinfo[0].purl;
+			const header = {
+				range: 'bytes=0-8191',
+				'accept-encoding': 'identity',
+			};
+			return request('GET', playurl, header).then((response) => {
+				if (response.statusCode < 200 || response.statusCode > 299)
+					return Promise.reject();
+				else return playurl;
+			});
 		});
 };
 
@@ -84,6 +93,7 @@ const track = (id) => {
 			['F000', '.flac'],
 			['M800', '.mp3'],
 			['M500', '.mp3'],
+			[null, null],
 		]
 			.slice(
 				headers.cookie || typeof window !== 'undefined'
```

**Comment by xsm1997** [comment]
测试通过，代码没问题。

但这样做有个坏处，就是如果qqmusic的flac 404了，它就会选择可用的m4a，往往是最低音质。而修改之前，404的话，会fallback到下一个源。这样qqmusic获取不到flac的歌曲，也会走酷我或者其他获取到flac，至少不是最低音质的m4a。我是使用FOLLOW_SOURCE_ORDER=true以确保优先从qqmusic获取音源。

所以我建议新增一个flag，专门处理qqmusic的这种情况。启用flag的时候fallback到m4a，禁用flag的时候不fallback，直接查询下一个音源。建议默认禁用这个flag，因为貌似大多数人都不只配置qqmusic一个源。

**Comment by 1715173329** [comment]
> 但这样做有个坏处，就是如果qqmusic的flac 404了，它就会选择可用的m4a，往往是最低音质。

这就是预期行为，其他音源也同样如此。
如果要加 flag，则应该是一个全局 flag，而不是某个特定的音源。

**Comment by xsm1997** [comment]
恩，我觉得应该加一个feature，筛选一下所有启用了的音源的最高音质，然后选择一个最高音质返回。新增一个flag控制这个，同时请求所有音源，全部返回之后，再进行筛选。这样也就不需要启用FOLLOW_SOURCE_ORDER了，因为我引入这个flag的目的也是选择最高音质（qqmusic那时候都有flac）。我有空pr一下吧。

**Comment by 1715173329** [comment]
> 恩，我觉得应该加一个feature，筛选一下所有启用了的音源的最高音质，然后选择一个最高音质返回。新增一个flag控制这个，同时请求所有音源，全部返回之后，再进行筛选。这样也就不需要启用FOLLOW_SOURCE_ORDER了，因为我引入这个flag的目的也是选择最高音质（qqmusic那时候都有flac）。我有空pr一下吧。

感谢大佬，同时也邀请您加入我们的组织共同开发（检查邮件或访问项目主页）。

**Comment by xsm1997** [comment]
感谢大佬的认可。我有空就把这个feature给加上。

**Comment by xsm1997** [comment]
#982
