### ISSUE TITLE
IOS和MacOS信任证书后依然为灰色歌曲，望修复。

### ISSUE THREAD

**Issue by MIAOBUSI** [UnblockNeteaseMusic/server#956]
<img width="513" alt="WeChate6740aad20cc0dd7874f73bba6eff110" src="https://user-images.githubusercontent.com/20589467/208301965-9d793562-9533-4f93-a77b-6cf3db93cb71.png">
<img width="1002" alt="WeChatd26afcbcd7b26f7a3e82f776e5fb8927" src="https://user-images.githubusercontent.com/20589467/208301972-2c1e17bf-0c45-4f76-ad7a-96868a6121c1.png">
<img width="396" alt="WeChatfcdb3d5597ec2274678ab05275b6bfe9" src="https://user-images.githubusercontent.com/20589467/208301976-e67f5953-0886-42d8-aef5-27f15df8278b.png">
<img width="398" alt="WeChat4c86cf9c9eac77ef88c579512925ca07" src="https://user-images.githubusercontent.com/20589467/208302337-67999a76-c516-4b68-b018-01cb87f4893f.png">
iOS系统版本为16.2 网易云版本为8.9.0
macOS系统版本13.1 网易云版本为2.3.11
运行环境为Lean Openwrt
目前Windows下信任证书后是能正常使用的，唯独iOS和macOS不行

**Comment by 1715173329** [comment]
命令行输入 unm-debug 打印调试报告

**Comment by MIAOBUSI** [comment]
插件版好像无法打印 输入unm-debug显示没有命令行

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Tianling ***@***.***>
发送时间: 2022年12月19日 2:56
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [UnblockNeteaseMusic/server] IOS和MacOS信任证书后依然为灰色歌曲，望修复。 (Issue #956)


命令行输入 unm-debug 打印调试报告

―

**Comment by 1715173329** [comment]
那就是你装的不是我们项目提供的 luci，查看我们项目主页。
