### ISSUE TITLE
nw.js网络连接失败

### ISSUE THREAD

**Issue by ChthoIly** [UnblockNeteaseMusic/server#968]
注册nw.js开机自启后可以在Windows服务里看见正常运行，网易云代理为http 127.0.0.1端口8080。在网易云里设置代理后点测试显示该代理可用，但是重启网易云后就显示网络连接失败。daemon下的错误日志也是空的。

作为23年的第一个Issue祝大家新年快乐(￣▽￣)~*

![image](https://user-images.githubusercontent.com/121737713/210294483-8ad509a8-6c2e-481d-8ef0-ff02cf086243.png)
![image](https://user-images.githubusercontent.com/121737713/210294388-661801b9-f0e8-47ba-b079-daaa9c6babd0.png)
![image](https://user-images.githubusercontent.com/121737713/210294669-7a276988-ae47-475c-a24b-78529dcf549f.png)

**Comment by 1715173329** [comment]
元旦快乐。

信任证书了吗？代理我不好说，听说网易云音乐新版引入了某些机制来检测这个劫持，真假未知。
我现在都是挂在路由器上直接用防火墙规则劫持的（

**Comment by ChthoIly** [comment]
信任了，之前跑本地nw.js都没问题的。最近重新装了一遍系统重新设置就发现突然用不了了。直接挂在路由器上有操作指南吗？有的话麻烦指一下路我试试看，谢谢

**Comment by 1715173329** [comment]
https://github.com/UnblockNeteaseMusic/luci-app-unblockneteasemusic
for openwrt，其他设备需要自行操作了

**Comment by ChthoIly** [comment]
换了一台旧笔记本装可以用了，应该是我电脑的问题。不知道它抽什么风了

**Comment by 1715173329** [comment]
之前也有人说过网易云有 bug，改了下载目录和缓存目录之后就容易出现这种问题。

**Comment by Wu-Chenyang** [comment]
相同的问题。。
