### ISSUE TITLE
[报错] hook error: ERR_OSSL_EVP_WRONG_FINAL_BLOCK_LENGTH

### ISSUE THREAD

**Issue by liukenny961** [UnblockNeteaseMusic/server#981]
### Bug 描述

网易云音乐版本：2.10.6
已安装两份证书
使用全局代理方式
开启后报错：
![Snipaste_2023-01-19_12-28-48](https://user-images.githubusercontent.com/65520199/213355365-eb3f58d4-fa89-4e50-85f2-75c8344f4e6a.png)

### 预期行为

UNM正常工作。

### 实际行为

开启后没有任何效果，无法解锁，powershell端报错。

### 复现步骤

文件夹打开powershell，node app.js启用。
网易云音乐设置代理HTTP，127.0.0.1，8080
歌曲无法播放，powershell端报错

### 日志内容

未找到日志……

### 网易云音乐版本号

2.10.6

### 操作系统

Win11 Dev Build 25276

### 条款

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint（仅 macOS 或 iOS）。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。
- [X] 我同意开发者没有任何义务必须解答我的问题，尤其是缺少恰当的描述和日志。

**Comment by pan93412** [comment]
> ### Bug 描述
> 网易云音乐版本：2.10.6 已安装两份证书 使用全局代理方式 开启后报错： ![Snipaste_2023-01-19_12-28-48](https://user-images.githubusercontent.com/65520199/213355365-eb3f58d4-fa89-4e50-85f2-75c8344f4e6a.png)
> 
> ### 预期行为
> UNM正常工作。
> 
> ### 实际行为
> 开启后没有任何效果，无法解锁，powershell端报错。
> 
> ### 复现步骤
> 文件夹打开powershell，node app.js启用。 网易云音乐设置代理HTTP，127.0.0.1，8080 歌曲无法播放，powershell端报错
> 
> ### 日志内容
> 未找到日志……
> 
> ### 网易云音乐版本号
> 2.10.6
> 
> ### 操作系统
> Win11 Dev Build 25276
> 
> ### 其他信息
> _No response_
> 
> ### 条款
> * [x]  我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
> * [x]  我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
> * [x]  我确认我已经启用了 HTTPS 端口。
> * [x]  我确认我已经正确设置了 EndPoint（仅 macOS 或 iOS）。
> * [x]  我确认我已经在对应的客户端正确安装了 CA 证书。
> * [x]  我同意开发者没有任何义务必须解答我的问题，尤其是缺少恰当的描述和日志。

日誌看起來已經提供了～

感覺是 NCM 的問題。

**Comment by liukenny961** [comment]
> > ### Bug 描述
> > 网易云音乐版本：2.10.6 已安装两份证书 使用全局代理方式 开启后报错： ![Snipaste_2023-01-19_12-28-48](https://user-images.githubusercontent.com/65520199/213355365-eb3f58d4-fa89-4e50-85f2-75c8344f4e6a.png)
> > ### 预期行为
> > UNM正常工作。
> > ### 实际行为
> > 开启后没有任何效果，无法解锁，powershell端报错。
> > ### 复现步骤
> > 文件夹打开powershell，node app.js启用。 网易云音乐设置代理HTTP，127.0.0.1，8080 歌曲无法播放，powershell端报错
> > ### 日志内容
> > 未找到日志……
> > ### 网易云音乐版本号
> > 2.10.6
> > ### 操作系统
> > Win11 Dev Build 25276
> > ### 其他信息
> > _No response_
> > ### 条款
> > 
> > * [x]   我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
> > * [x]   我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
> > * [x]   我确认我已经启用了 HTTPS 端口。
> > * [x]   我确认我已经正确设置了 EndPoint（仅 macOS 或 iOS）。
> > * [x]   我确认我已经在对应的客户端正确安装了 CA 证书。
> > * [x]   我同意开发者没有任何义务必须解答我的问题，尤其是缺少恰当的描述和日志。
> 
> 日誌看起來已經提供了～
> 
> 感覺是 NCM 的問題。

感谢感谢~
那暂时是没有解决办法吗🥺

**Comment by pan93412** [comment]
> > 日誌看起來已經提供了～
> > 感覺是 NCM 的問題。
> 
> 感谢感谢~ 那暂时是没有解决办法吗🥺

我會幫你掛 `help wanted`

**Comment by 1715173329** [comment]
1. https://github.com/nondanee/UnblockNeteaseMusic/issues/835#issuecomment-1373413270
2. #972

**Comment by liukenny961** [comment]
> 1. [2023年了，现在还可以用吗？我windows配置完，测试代理可用，但是无法添加播放音乐为什么？ nondanee/UnblockNeteaseMusic#835 (comment)](https://github.com/nondanee/UnblockNeteaseMusic/issues/835#issuecomment-1373413270)
> 2. [hook error: ERR_OSSL_EVP_WRONG_FINAL_BLOCK_LENGTH #972](https://github.com/UnblockNeteaseMusic/server/issues/972)

感谢感谢！🥰
但是第一个方法经测试无效……
看来大概是新版本NCM的问题，只能先退回旧版本看看了。

**Comment by 1715173329** [comment]
理论上这个问题不足以致命，我的版本号是 2.10.6.200601，只偶尔观测到这个错误，有点迷。
如果开启了本地 VIP 功能的话可以关掉试试。

**Comment by 1715173329** [comment]
Fixed by #1305
