### ISSUE TITLE
去广告的需求可以吗

### ISSUE THREAD

**Issue by xream** [UnblockNeteaseMusic/server#983]
### 需求描述

![image](https://user-images.githubusercontent.com/1210282/214088913-c1873e9d-8a0f-4465-877c-a565b2a9b7fa.png)

### 条款

- [X] 我同意开发者没有任何义务必须满足我的需求，尤其是高度自定义或特定于个人环境的需求。

**Comment by 1715173329** [comment]
会在最近几天加上。

**Comment by 1715173329** [comment]
可以请你确认一下 #988 是否按预期工作吗？

**Comment by xream** [comment]
好像不对

期望匹配的是类型以下几种 URL

```
http://183.136.182.19/eapi/ad/get?_nmclfl=1
http://interface3.music.163.com/eapi/ad/iyunIds?_nmclfl=1
http://interface3.music.163.com.163jiasu.com/eapi/ad/iyunIds?_nmclfl=1
```

我大概看了下 现在是在匹配 `/api/ad` 而且逻辑太靠后了...

我最开始发的截图里 是我写的比较粗暴的 最优先判断去广告

**Comment by 1715173329** [comment]
> 现在是在匹配 /api/ad

这是已经经过 unm 解析后的路径，是正确的。

> 而且逻辑太靠后了...

这部分没有影响，问题不大。

**Comment by xream** [comment]
不好意思 之前没仔细看代码...现在看明白了...
感觉好像不用等 request 请求之后再判断拦截吧

**Comment by 1715173329** [comment]
> 感觉好像不用等 request 请求之后再判断拦截吧

这里大概可以说是捕获请求啦，因为网易云音乐在不同平台下面的 api 有点小差异，这样做比较省事一点。

**Comment by xream** [comment]
👌🏻 那没问题了 我试了 iOS 最新版客户端拦截到了
可能文档里需要加一个说明 这里拦截了不代表客户端就不显示广告了...可能需要全新安装/配合其他工具
