### ISSUE TITLE
一起听功能无法使用

### ISSUE THREAD

**Issue by Lizh0111** [UnblockNeteaseMusic/server#987]
### Bug 描述

在使用网易云音乐windows端2.10.6版本中，启用代理后，无法使用一起听
我和朋友测试了我发送邀请二维码 结果为朋友那边（手机端）显示邀请已失效
朋友向我直接发起邀请，我这边显示正常加入，但加入后听歌不同步且朋友那边显示我未加入

### 日志内容

无

### 网易云音乐版本号

2.10.6

### 操作系统

windows10 x64 ltsc2019

### 条款

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint（仅 macOS 或 iOS）。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。
- [X] 我同意开发者没有任何义务必须解答我的问题，尤其是缺少恰当的描述和日志。

**Comment by 1715173329** [comment]
暂无法复现你的情况，我的版本号是 2.10.6.200601。有设定一些 UNM 的环境变量吗？

**Comment by Lizh0111** [comment]
启用了无损音源和使用了betterNCM（只加了几个美化插件）

**Comment by MicroCBer** [comment]
> 启用了无损音源和使用了betterNCM（只加了几个美化插件）

那么这有可能是BetterNCM的问题，之前群里有人报告，不过我也复现不了...建议卸载BetterNCM后再试
