### ISSUE TITLE
在betterNCM上，不能开黑胶

### ISSUE THREAD

**Issue by Entity-122425111303** [UnblockNeteaseMusic/server#998]
### Bug 描述

![image](https://user-images.githubusercontent.com/120158454/216317792-f2e56b7a-dd34-4ae6-8921-b74bfcc07876.png)
就是源码主页在这里
我就试试用环境变量开黑胶
![image](https://user-images.githubusercontent.com/120158454/216318200-c8f1ccc5-6f53-4005-a3f3-492553884cc5.png)
环境变量如图
可是没有黑胶
![image](https://user-images.githubusercontent.com/120158454/216318511-3383b5cb-ffb6-43b5-b07c-6cba917286e5.png)

### 预期行为

有黑胶

### 实际行为

没有黑胶

### 日志内容

额...这我咋找

### 网易云音乐版本号

2.10.6(Build:200601)(Patch:1:5ad43a6)

### 操作系统

win10 22H2

### 其他信息

我使用了betterNCM，不过他用的源码是这里的
参考[https://github.com/MicroCBer/BetterNCM.git](url)
[https://github.com/Entity-122425111303/UnblockCloudMusic.git](url)

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint（仅 macOS 或 iOS）。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by Entity-122425111303** [comment]
有没有可能是环境变量添加后没重启？

**Comment by 3131210** [comment]
fork到自己项目里，修改src/hook.js文件，把
const ENABLE_LOCAL_VIP =
	(process.env.ENABLE_LOCAL_VIP || '').toLowerCase() === 'true';

改成
const ENABLE_LOCAL_VIP = 'true';
保存后会自动编译，下载后覆盖到C:\betterncm\UnblockCloudMusic\UCM_server.exe
替换原本的文件

也可以下载我按照上面方法编译的文件，直接替换
https://wwmy.lanzoum.com/iCZlr0mpqz3c  密码:h1oq

**Comment by 1263892066** [comment]
请问一下，betterNCM的解灰插件在哪能下到？我的betterNCM插件库里面没有这个插件

**Comment by Entity-122425111303** [comment]
@1263892066 我的库里就有

**Comment by Entity-122425111303** [comment]
> 请问一下，betterNCM的解灰插件在哪能下到？我的betterNCM插件库里面没有这个插件，楼主能分享一下么？谢谢！

https://github.com/Entity-122425111303/UnblockCloudMusic @1263892066

**Comment by 3131210** [comment]
cmd运行下面的命令 设置用户变量也可以，你设置的是系统变量不行
setx ENABLE_FLAC true
setx ENABLE_LOCAL_VIP true

**Comment by 1263892066** [comment]
> 

非常感谢！
